#!/usr/bin/env php
<?php

if(isset($argv[1]) && 'config' == $argv[1]) {
  echo "graph_title Lichess players
graph_args --base 1000 -l 0
graph_vlabel players
graph_category lichess
players.label players
players.draw AREA
named.label named
named.draw AREA
";
  exit;
}

$url = 'http://en.lichess.org/monitor/players';

$curl = curl_init();
curl_setopt_array($curl, array(
      CURLOPT_URL             => $url,
      CURLOPT_PORT            => 80,
      CURLOPT_USERAGENT       => 'munin',
      CURLOPT_RETURNTRANSFER  => true,
      CURLOPT_TIMEOUT         => 2
    ));
$value = curl_exec($curl);
list($players, $named) = explode(' ', $value);

echo "players.value ".$players."\n";
echo "named.value ".$named."\n";
