daysUntilStale: 730
daysUntilClose: 14
exemptLabels:
  - prospect
  - foundational
  - wanted
  - bug
staleLabel: stale
markComment: >
  There has been no activity on this issue for 2 years. It will be
  automatically closed in 2 weeks.

  If the issue is still relevant, please briefly explain (or remove the label).
  Feel free to reopen at any time.
closeComment: false
