/*
 * This source is generated by bin/gen/licon.py. Run licon.py after changing public/font/lichess.sfd
 *
 * Constant names and values are pulled from private use characters defined in the sfd file.
 *
 * Character names can be edited in fontforge's "glyph info" dialog, or by editing the StartChar: line that
 * begins each character chunk in lichess.sfd
 *
 * To make these characters visible in your editor, install the lichess.ttf font (which is also generated by
 * licon.py) and then add it to your editor's font list.
 */

package lila.common

import lila.core.Icon

object licon:
  val Tools: Icon           = Icon("") // e000
  val Bullseye: Icon        = Icon("") // e001
  val Agent: Icon           = Icon("") // e002
  val Mic: Icon             = Icon("") // e003
  val BarChart: Icon        = Icon("") // e004
  val InfoCircle: Icon      = Icon("") // e005
  val ScreenDesktop: Icon   = Icon("") // e006
  val PhoneMobile: Icon     = Icon("") // e007
  val Multiboard: Icon      = Icon("") // e008
  val HeartOutline: Icon    = Icon("") // e009
  val FlagRacingKings: Icon = Icon("") // e00a
  val Crazyhouse: Icon      = Icon("") // e00b
  val Tshirt: Icon          = Icon("") // e00c
  val Heart: Icon           = Icon("") // e00d
  val RadioTower: Icon      = Icon("") // e00e
  val BellOutline: Icon     = Icon("") // e00f
  val Disc: Icon            = Icon("") // e010
  val Wings: Icon           = Icon("") // e011
  val DiscOutline: Icon     = Icon("") // e012
  val Handset: Icon         = Icon("") // e013
  val ArrowThruApple: Icon  = Icon("") // e014
  val CautionTriangle: Icon = Icon("") // e015
  val Link: Icon            = Icon("") // e016
  val Rabbit: Icon          = Icon("") // e017
  val NodeBranching: Icon   = Icon("") // e018
  val Gear: Icon            = Icon("") // e019
  val Reload: Icon          = Icon("") // e01a
  val DieSix: Icon          = Icon("") // e01b
  val FlagKingHill: Icon    = Icon("") // e01c
  val FlameBlitz: Icon      = Icon("") // e01d
  val Feather: Icon         = Icon("") // e01e
  val Turtle: Icon          = Icon("") // e01f
  val FlagChessboard: Icon  = Icon("") // e020
  val ArcheryTarget: Icon   = Icon("") // e021
  val ThreeCheckStack: Icon = Icon("") // e022
  val UploadCloud: Icon     = Icon("") // e023
  val ExternalArrow: Icon   = Icon("") // e024
  val AnalogTv: Icon        = Icon("") // e025
  val RssFeed: Icon         = Icon("") // e026
  val StudyBoard: Icon      = Icon("") // e027
  val Shield: Icon          = Icon("") // e028
  val InkQuill: Icon        = Icon("") // e029
  val Target: Icon          = Icon("") // e02a
  val Crown: Icon           = Icon("") // e02b
  val LineGraph: Icon       = Icon("") // e02c
  val GraduateCap: Icon     = Icon("") // e02d
  val PaperAirplane: Icon   = Icon("") // e02e
  val ZoomIn: Icon          = Icon("") // e02f
  val Expand: Icon          = Icon("") // e030
  val Atom: Icon            = Icon("") // e031
  val List: Icon            = Icon("") // e032
  val Antichess: Icon       = Icon("") // e033
  val Microscope: Icon      = Icon("") // e034
  val ChasingArrows: Icon   = Icon("") // e035
  val CrownElite: Icon      = Icon("") // e036
  val Funnel: Icon          = Icon("") // e037
  val Checkmark: Icon       = Icon("") // e038
  val InternalArrow: Icon   = Icon("") // e039
  val PlayTriangle: Icon    = Icon("") // e03a
  val GreaterThan: Icon     = Icon("") // e03b
  val LessThan: Icon        = Icon("") // e03c
  val DiscBig: Icon         = Icon("") // e03d
  val DiscBigOutline: Icon  = Icon("") // e03e
  val X: Icon               = Icon("") // e03f
  val ArrowDownRight: Icon  = Icon("") // e040
  val ArrowUpRight: Icon    = Icon("") // e041
  val PlusButton: Icon      = Icon("") // e042
  val MinusButton: Icon     = Icon("") // e043
  val Fire: Icon            = Icon("") // e044
  val DownTriangle: Icon    = Icon("") // e045
  val UpTriangle: Icon      = Icon("") // e046
  val Bullet: Icon          = Icon("") // e047
  val Swords: Icon          = Icon("") // e048
  val JumpLast: Icon        = Icon("") // e049
  val JumpFirst: Icon       = Icon("") // e04a
  val JumpNext: Icon        = Icon("") // e04b
  val JumpPrev: Icon        = Icon("") // e04c
  val Pause: Icon           = Icon("") // e04d
  val Hamburger: Icon       = Icon("") // e04e
  val Globe: Icon           = Icon("") // e04f
  val Book: Icon            = Icon("") // e050
  val BarGraph: Icon        = Icon("") // e051
  val Keypad: Icon          = Icon("") // e052
  val Berserk: Icon         = Icon("") // e053
  val Padlock: Icon         = Icon("") // e054
  val FlagOutline: Icon     = Icon("") // e055
  val BubbleSpeech: Icon    = Icon("") // e056
  val BubbleConvo: Icon     = Icon("") // e057
  val Envelope: Icon        = Icon("") // e058
  val Group: Icon           = Icon("") // e059
  val Trophy: Icon          = Icon("") // e05a
  val ThumbsUp: Icon        = Icon("") // e05b
  val Back: Icon            = Icon("") // e05c
  val CautionCircle: Icon   = Icon("") // e05d
  val NotAllowed: Icon      = Icon("") // e05e
  val RandomColor: Icon     = Icon("") // e05f
  val Pencil: Icon          = Icon("") // e060
  val Cogs: Icon            = Icon("") // e061
  val Tag: Icon             = Icon("") // e062
  val Clock: Icon           = Icon("") // e063
  val Trash: Icon           = Icon("") // e064
  val User: Icon            = Icon("") // e065
  val StarOutline: Icon     = Icon("") // e066
  val Star: Icon            = Icon("") // e067
  val MoreTriangle: Icon    = Icon("") // e068
  val Eye: Icon             = Icon("") // e069
  val Power: Icon           = Icon("") // e06a
  val Download: Icon        = Icon("") // e06b
  val Search: Icon          = Icon("") // e06c
  val Forward: Icon         = Icon("") // e06d
  val UltraBullet: Icon     = Icon("") // e06e
  val Storm: Icon           = Icon("") // e06f
  val Clipboard: Icon       = Icon("") // e070
  val Cancel: Icon          = Icon("") // e071
  val Ibeam: Icon           = Icon("") // e072
  val Voice: Icon           = Icon("") // e073
  val Mask: Icon            = Icon("") // e074
  val Move: Icon            = Icon("") // e075
  val OneHalf: Icon         = Icon("") // e076
  val Mute: Icon            = Icon("") // e077
  val AccountCircle: Icon   = Icon("") // e078
  val Logo: Icon            = Icon("") // e079
