/*
 * This source is generated by bin/gen/licon.py. Run bin/licon.py after changing public/font/lichess.sfd
 *
 * Constant names and values are pulled from private use characters defined in the sfd file.
 *
 * Character names can be edited in fontforge's "glyph info" dialog, or by editing the StartChar: line that
 * begins each character chunk in lichess.sfd
 *
 * To make these characters visible in your editor, install the lichess.ttf font (which is also generated by
 * licon.py) and then add it to your editor's font list.
 *
 * You could google 'how to install fonts', but it is generally considered best practice to ping @1vader on
 * discord about these matters.
 */

package lila.common

object licon:
  val Tools           = "" // e000
  val Bullseye        = "" // e001
  val Agent           = "" // e002
  val Mic             = "" // e003
  val BarChart        = "" // e004
  val InfoCircle      = "" // e005
  val ScreenDesktop   = "" // e006
  val PhoneMobile     = "" // e007
  val Multiboard      = "" // e008
  val HeartOutline    = "" // e009
  val FlagRacingKings = "" // e00a
  val Crazyhouse      = "" // e00b
  val Tshirt          = "" // e00c
  val Heart           = "" // e00d
  val RadioTower      = "" // e00e
  val BellOutline     = "" // e00f
  val Disc            = "" // e010
  val Wings           = "" // e011
  val DiscOutline     = "" // e012
  val Handset         = "" // e013
  val ArrowThruApple  = "" // e014
  val CautionTriangle = "" // e015
  val Link            = "" // e016
  val Rabbit          = "" // e017
  val NodeBranching   = "" // e018
  val Gear            = "" // e019
  val DieSix          = "" // e01b
  val FlagKingHill    = "" // e01c
  val FlameBlitz      = "" // e01d
  val Feather         = "" // e01e
  val Turtle          = "" // e01f
  val FlagChessboard  = "" // e020
  val ArcheryTarget   = "" // e021
  val ThreeCheckStack = "" // e022
  val UploadCloud     = "" // e023
  val ExternalArrow   = "" // e024
  val AnalogTv        = "" // e025
  val RssFeed         = "" // e026
  val StudyBoard      = "" // e027
  val Shield          = "" // e028
  val InkQuill        = "" // e029
  val Target          = "" // e02a
  val Crown           = "" // e02b
  val LineGraph       = "" // e02c
  val GraduateCap     = "" // e02d
  val PaperAirplane   = "" // e02e
  val ZoomIn          = "" // e02f
  val Expand          = "" // e030
  val Atom            = "" // e031
  val List            = "" // e032
  val Antichess       = "" // e033
  val Microscope      = "" // e034
  val ChasingArrows   = "" // e035
  val CrownElite      = "" // e036
  val Funnel          = "" // e037
  val Checkmark       = "" // e038
  val InternalArrow   = "" // e039
  val PlayTriangle    = "" // e03a
  val GreaterThan     = "" // e03b
  val LessThan        = "" // e03c
  val DiscBig         = "" // e03d
  val DiscBigOutline  = "" // e03e
  val X               = "" // e03f
  val ArrowDownRight  = "" // e040
  val ArrowUpRight    = "" // e041
  val PlusButton      = "" // e042
  val Reload          = "" // e043
  val Fire            = "" // e044
  val DownTriangle    = "" // e045
  val UpTriangle      = "" // e046
  val Bullet          = "" // e047
  val Swords          = "" // e048
  val JumpLast        = "" // e049
  val JumpFirst       = "" // e04a
  val JumpNext        = "" // e04b
  val JumpPrev        = "" // e04c
  val Pause           = "" // e04d
  val Hamburger       = "" // e04e
  val Globe           = "" // e04f
  val Book            = "" // e050
  val BarGraph        = "" // e051
  val Keypad          = "" // e052
  val Berserk         = "" // e053
  val Padlock         = "" // e054
  val FlagOutline     = "" // e055
  val BubbleSpeech    = "" // e056
  val BubbleConvo     = "" // e057
  val Envelope        = "" // e058
  val Group           = "" // e059
  val Trophy          = "" // e05a
  val ThumbsUp        = "" // e05b
  val Back            = "" // e05c
  val CautionCircle   = "" // e05d
  val NotAllowed      = "" // e05e
  val RandomColor     = "" // e05f
  val Pencil          = "" // e060
  val Cogs            = "" // e061
  val Tag             = "" // e062
  val Clock           = "" // e063
  val Trash           = "" // e064
  val User            = "" // e065
  val StarOutline     = "" // e066
  val Star            = "" // e067
  val MoreTriangle    = "" // e068
  val Eye             = "" // e069
  val Power           = "" // e06a
  val Download        = "" // e06b
  val Search          = "" // e06c
  val Forward         = "" // e06d
  val UltraBullet     = "" // e06e
  val Storm           = "" // e06f
  val Clipboard       = "" // e070
  val Cancel          = "" // e071
  val Ibeam           = "" // e072
  val Voice           = "" // e073
  val Mask            = "" // e074
  val Move            = "" // e075
