// Generated by @build/index.mjs to export the bots directory from src/index.ts
//
// Relaunch ui/build to regenerate (the bots directory is not watched).

export * from './bots/agatha';
export * from './bots/babyHoward';
export * from './bots/beatrice';
export * from './bots/coral';
export * from './bots/dansby';
export * from './bots/elsieZero';
export * from './bots/gary';
export * from './bots/ghost';
export * from './bots/greta';
export * from './bots/grunt';
export * from './bots/helena';
export * from './bots/henry';
export * from './bots/larry';
export * from './bots/listress';
export * from './bots/louise';
export * from './bots/maia';
export * from './bots/marco';
export * from './bots/mitsoko';
export * from './bots/nacho';
export * from './bots/owen';
export * from './bots/shark';
export * from './bots/spectre';
export * from './bots/terrence';
