print("Users");
var oUsers = db.user;
var nUsers = db.user2;
nUsers.drop();
db.fos_user_group.drop();
oUsers.find().forEach(function(user) {
  user.oid = user._id.toString();
  user._id = user.usernameCanonical;
  if (user.elo < 800) user.elo = 800;
  delete user["usernameCanonical"];
  delete user["lastLogin"];
  delete user["isOnline"];
  delete user["gameConfigs"];
  delete user["email"];
  delete user["emailCanonical"];
  delete user["updatedAt"];
  delete user["algorithm"];
  delete user["rememberMeToken"];
  nUsers.insert(user);
});
nUsers.ensureIndex({enabled: 1});
nUsers.ensureIndex({enabled: 1, elo: -1});
