nodeVersion: 24.20.0
pmOnFail: warn
autoDedupe: true
packages:
  - 'bin'
  - 'ui/*'
  - 'ui/@types/*'
ignoredOptionalDependencies:
  - '*arm-*'
  - '*ia32-*'
  - '*-ia32*'
  - '*loong64-*'
  - '*-loong64*'
  - '*mips64el-*'
  - '*-mips64el*'
  - '*ppc64-*'
  - '*-ppc64*'
  - '*riscv64-*'
  - '*-riscv64*'
  - '*s390x-*'
  - '*-s390x*'
  - '*aix-*'
  - '*-aix*'
  - '*android-*'
  - '*-android*'
  - '*freebsd-*'
  - '*-freebsd*'
  - '*openbsd-*'
  - '*-openbsd*'
  - '*openharmony-*'
  - '*-openharmony*'
  - '*netbsd-*'
  - '*-netbsd*'
  - '*sunos-*'
  - '*-sunos*'
allowBuilds:
  esbuild: true
  protobufjs: false
overrides:
  fast-uri: ^3.1.7
  undici: ^8.10.2
patchedDependencies:
  '@toast-ui/editor@3.2.2': ui/bits/patches/@toast-ui__editor.patch
minimumReleaseAgeExclude:
  - '@lichess-org/*'
  - pnpm
