nodeVersion: 24.20.0
pmOnFail: warn
autoDedupe: true
packages:
  - 'bin'
  - 'ui/*'
  - 'ui/@types/*'
allowBuilds:
  esbuild: true
  protobufjs: false
overrides:
  fast-uri: ^3.1.7
  undici: ^8.10.2
patchedDependencies:
  '@toast-ui/editor@3.2.2': ui/bits/patches/@toast-ui__editor.patch
minimumReleaseAgeExclude:
  - '@lichess-org/*'
  - pnpm
