#!/bin/sh -e

# Starts a dev console to compile and run lichess.

# Usage:
# ./run
# Then in the sbt console:
# ~run

# We use .sbtopts instead
export SBT_OPTS=""

# For development without nginx (not recommended).
export SERVE_ASSETS=0

if [ ! -f "conf/application.conf" ]; then
  cp conf/application.conf.default conf/application.conf
fi

echo "
   |\_    _ _      _
  /o \\\\  | (_) ___| |__   ___  ___ ___   ___  _ __ __ _
 (_. ||  | | |/ __| '_ \ / _ \/ __/ __| / _ \| '__/ _\` |
  /__\\\\  | | | (__| | | |  __/\__ \__ \| (_) | | | (_| |
  )___(  |_|_|\___|_| |_|\___||___/___(_)___/|_|  \__, |
                                                  |___/"
version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}')
echo Java version: "$version"

sbt "$@"
