#!/bin/sh -e

# Starts a dev console to compile and run lichess.

# Usage:
# ./run
# Then in the sbt console:
# ~run

# Yes it needs tons of memory to build. Go for 2048M  if you have them.
export JAVA_OPTS="-Xms1024M -Xmx2048M -XX:+UseParallelGC -XX:+ExitOnOutOfMemoryError"
export SBT_OPTS=""

# For development without nginx (not recommended).
export SERVE_ASSETS=0

echo "
   |\_    _ _      _
  /o \\\\  | (_) ___| |__   ___  ___ ___   ___  _ __ __ _
 (_. ||  | | |/ __| '_ \ / _ \/ __/ __| / _ \| '__/ _\` |
  /__\\\\  | | | (__| | | |  __/\__ \__ \| (_) | | | (_| |
  )___(  |_|_|\___|_| |_|\___||___/___(_)___/|_|  \__, |
                                                  |___/"
version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}')
echo Java version: "$version"
echo Java options: $JAVA_OPTS

sbt "$@"
