name: Bug report
description: Report something not working on the website. See below for mobile app.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        <b>Thank you for reporting an issue. Before submitting, please [search existing issues](https://github.com/lichess-org/lila/issues) to confirm this is not a duplicate issue.</b>
  - type: textarea
    id: url
    attributes:
      label: Exact URL of where the bug happened
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the bug
      description: Provide precise step by step instructions on how to reproduce the bug
      placeholder: |
        1. Go to ...
        2. Click ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: What happened instead?
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      description: Specify the OS you are using to access Lichess (e.g. Windows 11)
    validations:
      required: true
  - type: input
    attributes:
      label: Browser and version (or alternate access method)
      description: Specify the browser and version you are using (e.g. Firefox 110.0). Otherwise, specify your access method (such as API).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Provide any additional information that will give more context for the issue you are encountering.
        Screenshots can be added by clicking this area and then pasting or dragging them in.
    validations:
      required: false
