nodeVersion: 24.20.0
allowBuilds:
  esbuild: true
ignoredOptionalDependencies:
  - '@esbuild/*-arm'
  - '@esbuild/*-ia32'
  - '@esbuild/*-loong64'
  - '@esbuild/*-mips64el'
  - '@esbuild/*-ppc64'
  - '@esbuild/*-riscv64'
  - '@esbuild/*-s390x'
  - '@esbuild/aix-*'
  - '@esbuild/android-*'
  - '@esbuild/freebsd-*'
  - '@esbuild/openbsd-*'
  - '@esbuild/openharmony-*'
  - '@esbuild/netbsd-*'
  - '@esbuild/sunos-*'
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - sasso-native-* # 2026/10/07 remove me
  - sasso # 2026/10/07 remove me
