nodeVersion: 24.20.0
autoDedupe: true
allowBuilds:
  esbuild: true
ignoredOptionalDependencies:
  - '*arm-*'
  - '*ia32-*'
  - '*loong64-*'
  - '*mips64el-*'
  - '*ppc64-*'
  - '*riscv64-*'
  - '*s390x-*'
  - '*aix-*'
  - '*android-*'
  - '*freebsd-*'
  - '*openbsd-*'
  - '*openharmony-*'
  - '*netbsd-*'
  - '*sunos-*'
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - pnpm
  - sasso-native-* # 2026/10/07 remove me
  - sasso # 2026/10/07 remove me
