openapi: "3.1.0"
info:
  version: 2.0.0
  title: Lishogi.org API reference
  contact:
    name: "Lishogi.org API"
    url: "https://lishogi.org/api"
    email: "contact@lishogi.org"
  x-logo:
    url: https://lishogi1.org/assets/logo/lishogi-favicon-128.png
  description: |
    # Introduction
    Welcome to the reference for the Lishogi API! Lishogi is free/libre,
    open-source shogi server forked from lichess powered by volunteers and donations.

    Currently this page is a work in progress, certain information here might be wrong and incorrect!
    Expect it to be done during 2022.
    - Get help in the [Lishogi Discord channel](https://discord.gg/YFtpMGg3rR)
    - [Contribute to this documentation on Github](https://github.com/WandererXII/lishogi/blob/master/public/doc/lishogi-api.yaml)
    - Check out [Lishogi widgets to embed in your website](https://lishogi.org/developers)

    ## Endpoint
    All requests go to `https://lishogi.org` (unless otherwise specified).

    ## Rate limiting
    All requests are rate limited using various strategies,
    to ensure the API remains responsive for everyone.
    Only make one request at a time.
    If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429),
    please wait a full minute before resuming API usage.

    ## Streaming with ND-JSON
    Some API endpoints stream their responses as [Newline Delimited JSON a.k.a. **nd-json**](http://ndjson.org/), with one JSON object per line.

    Here's a [JavaScript utility function (for lichess)](https://gist.github.com/ornicar/a097406810939cf7be1df8ea30e94f3e) to help reading NDJSON streamed responses.
servers:
  - url: https://lishogi.org
tags:
- name: Account
  description: |
    Read and write account information and preferences.
    <https://lishogi.org/account/preferences/game-display>
- name: Users
  description: |
    Access registered users on Lishogi.
    <https://lishogi.org/player>
- name: Relations
  description: |
    Access relations between users.
- name: Games
  description: |
    Access games played on Lishogi.
    <https://lishogi.org/games>
- name: TV
  description: |
    Access Lishogi TV channels and games.
    <https://lishogi.org/tv> & <https://lishogi.org/games>
- name: Puzzles
  description: |
    Access Lishogi [puzzle history and dashboard](https://lishogi.org/training).

    For a list of our puzzle themes with their description, check out the [theme translation file](https://github.com/WandererXII/lishogi/blob/master/translation/source/puzzleTheme.xml).
- name: Teams
  description: |
    Access and manage Lishogi teams and their members.
    <https://lishogi.org/team>
- name: Board
  description: "Play on Lishogi with third-party clients.\n
  \ Works with normal Lishogi accounts. Engine play or assistance is forbidden.\n\n\
  \n### Features\n\
  \ - [Stream incoming shogi moves](#operation/boardGameStream)\n\
  \ - [Play shogi moves](#operation/boardGameMove)\n\
  \ - [Read](#operation/boardGameStream) and [write](#operation/boardGameChatPost) in the player and spectator chats\n\
  \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges\n\
  \ - [Abort](#operation/boardGameAbort) and [resign](#operation/boardGameResign) games\n\
  \ - Compatible with normal Lishogi accounts\n\n
  \n### Restrictions\n\
  \ - Engine assistance, or any kind of outside help, is strictly forbidden\n\
  \ - Time controls: [Rapid, Classical and Correspondence](https://lishogi.org/faq#time-controls) only.\n\
  \   For direct challenges and games vs AI, Blitz is also possible.\n\
  \n### Links\n\
  \ - [Announcement](https://lichess.org/blog/XlRW5REAAB8AUJJ-/welcome-lishogi-boards)\n\
  \ - [Implementation example](https://github.com/lishogi-org/api-demo) and [live demo](https://lichess-org.github.io/api-demo/) for lichess\n\n
  \ - [Lishogi discord bot](https://top.gg/bot/842330057841049600)"
- name: Bot
  description: "Play on Lishogi as a bot. Allows engine play.\n
  \ Only works with [Bot accounts](#operation/botAccountUpgrade).\n\n\
  \n### Features\n\
  \ - [Stream incoming shogi moves](#operation/botGameStream)\n\
  \ - [Play shogi moves](#operation/botGameMove)\n\
  \ - [Read](#operation/botGameStream) and [write](#operation/botGameChat) in the player and spectator chats\n\
  \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges\n\
  \ - [Abort](#operation/botGameAbort) and [resign](#operation/botGameResign) games\n\
  \ - Engine assistance is allowed\n\
  \n### Restrictions\n\
  \ - Bots can only play challenge games: tournaments are off-limits\n\
  \n### Integrations\n\
  \ - [Python3 lishogi-bot](https://github.com/TheYoBots/Lishogi-Bot) (official)\n\
  \ - Yours? Please make [an issue or pull request](https://github.com/lishogi-org/api).\n\
  \n### Links\n\
  \ - Join the [Lishogi Bots team](https://lishogi.org/team/lishogi-bots) with your bot account\n\
  \ - [Get help in the discord channel](https://discord.gg/FvTuNMx4bY)\n\
  \ - Watch [Lishogi Bot TV](https://lishogi.org/tv/bot)"
- name: Challenges
  description: |
    Send and receive challenges to play.
- name: Arena tournaments
  description: |
    Access Arena tournaments played on Lishogi.
    [Official Arena tournaments](https://lishogi.org/tournament) are maintained by Lishogi,
    but you can [create your own Arena tournaments](https://lishogi.org/tournament/new) as well.
- name: Simuls
  description: |
    Access simuls played on Lishogi.
    <https://lishogi.org/simul>
- name: Studies
  description: |
    Access Lishogi studies.
    <https://lishogi.org/study>
- name: Messaging
  description: |
    Private messages with other players.
    <https://lishogi.org/inbox>
- name: Analysis
  description: |
    Access Lishogi cloud evaluations database.
    <https://lishogi.org/analysis>
paths:
  /api/users/status:
    get:
      operationId: apiUsersStatus
      summary: Get real-time users status
      description: |
        Read the `online`, `playing` and `streaming` flags of several users.

        This API is very fast and cheap on lishogi side.
        So you can call it quite often (like once every 5 seconds).

        Use it to track players and know when they're connected on lishogi and playing games.
      tags:
        - Users
      security: []
  /player:
    get:
      operationId: player
      summary: Get all top 10
      tags:
        - Users
      security: []
      description: |
        Get the top 10 players for each speed and variant.

        See <https://lishogi.org/player>.
  /player/top/{nb}/{perfType}:
    get:
      operationId: playerTopNbPerfType
      summary: Get one leaderboard
      tags:
        - Users
      security: []
      description: |
        Get the leaderboard for a single speed or variant (a.k.a. `perfType`).
        There is no leaderboard for correspondence or puzzles.

        See <https://lishogi.org/player/top/200/bullet>.
  /api/user/{username}:
    get:
      operationId: apiUser
      summary: Get user public data
      description: |
        Read public data of a user.
      tags:
        - Users
      security: []
  /api/user/{username}/rating-history:
    get:
      operationId: apiUserRatingHistory
      summary: Get rating history of a user
      description: |
        Read rating history of a user, for all perf types.
        There is at most one entry per day.
        Format of an entry is `[year, month, day, rating]`.
        `month` starts at zero (January).
      tags:
        - Users
      security: []
  /api/user/{username}/activity:
    get:
      operationId: apiUserActivity
      summary: Get user activity
      description: |
        Read data to generate the activity feed of a user.
      tags:
        - Users
      security: []
  /api/puzzle/daily:
    get:
      operationId: apiPuzzleDaily
      summary: Get the daily puzzle
      description: |
        Get the daily Lishogi puzzle in JSON format.
      tags:
        - Puzzles
      security: []
  /api/puzzle/activity:
    get:
      operationId: apiPuzzleActivity
      summary: Get your puzzle activity
      description: |
        Download your puzzle activity in [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Puzzle activity is sorted by reverse chronological order (most recent first)

        We recommend streaming the response, for it can be very long.
      tags:
        - Puzzles
      security:
        - OAuth2: ["puzzle:read"]
  /api/puzzle/dashboard/{days}:
    get:
      operationId: apiPuzzleDashboard
      summary: Get your puzzle dashboard
      description: |
        Download your [puzzle dashboard](https://lishogi.org/training/dashboard/30/dashboard) as JSON.

        Also includes all puzzle themes played, with aggregated results.

        Allows re-creating the [improvement/strengths](https://lishogi.org/training/dashboard/30/improvementAreas) interfaces.
      tags:
        - Puzzles
      security:
        - OAuth2: ["puzzle:read"]
  /api/users:
    post:
      operationId: apiUsers
      summary: Get users by ID
      tags:
        - Users
      security: []
      description: |
        Get up to 300 users by their IDs. Users are returned in the same order as the IDs.

        The method is `POST` so a longer list of IDs can be sent in the request body.
  /api/account:
    get:
      operationId: accountMe
      summary: Get my profile
      description: |
        Public information about the logged in user.
      tags:
        - Account
      security:
        - OAuth2: []
  /api/account/email:
    get:
      operationId: accountEmail
      summary: Get my email address
      description: |
        Read the email address of the logged in user.
      tags:
        - Account
      security:
        - OAuth2: ["email:read"]
  /api/account/preferences:
    get:
      operationId: account
      summary: Get my preferences
      description: |
        Read the preferences of the logged in user.

        - <https://lishogi.org/account/preferences/game-display>
        - <https://github.com/WandererXII/lishogi/blob/master/modules/pref/src/main/Pref.scala>
      tags:
        - Account
      security:
        - OAuth2: ["preference:read"]
  /api/account/kid:
    get:
      operationId: accountKid
      summary: Get my kid mode status
      description: |
        Read the kid mode status of the logged in user.

        - <https://lishogi.org/account/kid>
      tags:
        - Account
      security:
        - OAuth2: ["preference:read"]
    post:
      operationId: accountKidPost
      summary: Set my kid mode status
      description: |
        Set the kid mode status of the logged in user.

        - <https://lishogi.org/account/kid>
      tags:
        - Account
      security:
        - OAuth2: ["preference:write"]
  /game/export/{gameId}:
    get:
      operationId: gameKif
      summary: Export one game
      description: |
        Download one game in either KIF or JSON format.

        Ongoing games have their last 3 moves omitted, after move 5.
      tags:
        - Games
      security: []
  /api/user/{username}/current-game:
    get:
      operationId: apiUserCurrentGame
      summary: Export ongoing game of a user
      description: |
        Download the ongoing game, or the last game played, of a user.
        Available in either KIF or JSON format.
        If the game is ongoing, the 3 last moves are omitted.
      tags:
        - Games
      security: []
  /api/games/user/{username}:
    get:
      operationId: apiGamesUser
      summary: Export games of a user
      description: |
        Download all games of any user in KIF or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Games are sorted by reverse chronological order (most recent first).

        We recommend streaming the response, for it can be very long.
        <https://lishogi.org/@/YoBot_v2> for instance has more than 15,000 games.

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Authentication) request: 30 games per second
          - Authenticated, downloading your own games: 60 games per second
      tags:
        - Games
      security:
        - OAuth2: []
  /api/stream/games-by-users:
    post:
      operationId: gamesByUsers
      summary: Stream games of users
      description: |
        Stream the games played between a list of users, in real time.
        Only games where **both players** are part of the list are included.

        By default, games are only sent to the stream when they start.
        To also get all ongoing games at the beginning of the stream, use the `withCurrentGames` flag.

        Maximum number of users: 300.

        Games are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        The method is `POST` so a longer list of IDs can be sent in the request body.
      tags:
        - Games
      security: []
  /api/account/playing:
    get:
      operationId: apiAccountPlaying
      summary: Get my ongoing games
      description: |
        Get the ongoing games of the current user.
        Real-time and correspondence games are included.
        The most urgent games are listed first.
      tags:
        - Games
      security:
        - OAuth2: []
  /api/stream/game/{id}:
    get:
      operationId: streamGame
      summary: Stream moves of a game
      description: |
        Stream positions and moves of any ongoing game, in [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        A description of the game is sent as a first message.
        Then a message is sent each time a move is played.
        Finally a description of the game is sent when it finishes, and the stream is closed.

        After move 5, the stream intentionally remains 3 moves behind the game status, as to prevent cheat bots from using this API.

        No more than 8 game streams can be opened at the same time from the same IP address.
      tags:
        - Games
      security: []
  /api/tv/channels:
    get:
      operationId: tvChannels
      summary: Get current TV games
      description: |
        Get basic info about the best games being played for each speed and variant,
        but also computer games and bot games.

        See [lishogi.org/tv](https://lishogi.org/tv).
      tags:
        - TV
      security: []
  /api/tv/feed:
    get:
      operationId: tvFeed
      summary: Stream current TV game
      description: |
        Stream positions and moves of the current [TV game](https://lishogi.org/tv) in [ndjson](#section/Introduction/Streaming-with-ND-JSON).
        A summary of the game is sent as a first message, and when the featured game changes.

        Try it with `curl https://lishogi.org/api/tv/feed`.
      tags:
        - TV
      security: []
  /api/tv/{channel}:
    get:
      operationId: tvChannelGames
      summary: Get best ongoing games of a TV channel
      description: |
        Get a list of ongoing games for a given TV channel. Similar to [lishogi.org/games](https://lishogi.org/games).

        Available in kifu or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request Accept header.
      tags:
        - TV
      security: []
  /api/tournament:
    get:
      operationId: apiTournament
      summary: Get current tournaments
      description: |
        Get recently finished, ongoing, and upcoming tournaments.

        This API is used to display the [Lishogi tournament schedule](https://lishogi.org/tournament).
      tags:
        - "Arena tournaments"
      security: []
    post:
      operationId: apiTournamentPost
      summary: Create a new Arena tournament
      description: |
        Create a public or private Arena tournament.

        This endpoint mirrors the form on <https://lishogi.org/tournament/new>.

        You can create up to 12 public tournaments per day, or 24 private tournaments.

        A team battle can be created by specifying the `teambBattleByTeam` argument.
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}:
    get:
      operationId: tournament
      summary: Get info about an Arena tournament
      description: |
        Get detailed info about recently finished, current, or upcoming tournament's duels, player standings, and other info.
      tags:
        - "Arena tournaments"
      security: []
  /api/tournament/{id}/games:
    get:
      operationId: gamesByTournament
      summary: Export games of an Arena tournament
      description: |
        Download games of a tournament in KIF or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Games are sorted by reverse chronological order (most recent first).

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Authentication) request: 30 games per second
      tags:
        - "Arena tournaments"
      security: []
  /api/tournament/{id}/results:
    get:
      operationId: resultsByTournament
      summary: Get results of an Arena tournament
      description: |
        Players of an Arena tournament, with their score and performance, sorted by rank (best first).

        **Players are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON)**, i.e. one JSON object per line.

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      tags:
        - "Arena tournaments"
      security: []
  /api/tournament/{id}/teams:
    get:
      operationId: teamsByTournament
      summary: Get team standing of a team battle
      description: |
        Teams of a team battle tournament, with top players, sorted by rank (best first).
      tags:
        - "Arena tournaments"
      security: []
  /api/user/{username}/tournament/created:
    get:
      operationId: apiUserNameTournamentCreated
      summary: Get tournaments created by a user
      description: |
        Get all tournaments created by a given user.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        Tournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - "Arena tournaments"
      security: []
  /study/{studyId}/{chapterId}.kif:
    get:
      operationId: studyChapterKif
      summary: Export one study chapter
      description: |
        Download one study chapter in KIF format.
      tags:
        - Studies
      security: []
  /api/study/{studyId}.kif:
    get:
      operationId: studyAllChaptersKif
      summary: Export all chapters
      description: |
        Download all chapters of a study in KIF format.
      tags:
        - Studies
      security: []
  /study/by/{username}/export.kif:
    get:
      operationId: studyExportAllKif
      summary: Export all studies of a user
      description: |
        Download all chapters of all studies of a user in KIF format.

        If authenticated, then all public, unlisted, and private studies are included.

        If not, only public, listed studies are included.
      tags:
        - Studies
      security:
        - OAuth2: ["study:read"]
  /api/simul:
    get:
      operationId: apiSimul
      summary: Get current simuls
      description: |
        Get recently finished, ongoing, and upcoming simuls.
      tags:
        - Simuls
      security: []
  /api/team/{teamId}:
    get:
      operationId: teamShow
      summary: Get a single team
      description: Infos about a team
      tags:
        - Teams
      security: []
  /api/team/all:
    get:
      operationId: teamAll
      summary: Get popular teams
      description: |
        Paginator of the most popular teams.
      tags:
        - Teams
      security: []
  /api/team/of/{username}:
    get:
      operationId: teamOfUsername
      summary: Teams of a player
      description: |
        All the teams a player is a member of.
      tags:
        - Teams
      security: []
  /api/team/search:
    get:
      operationId: teamSearch
      summary: Search teams
      description: |
        Paginator of team search results for a keyword.
      tags:
        - Teams
      security: []
  /api/team/{teamId}/users:
    get:
      operationId: teamIdUsers
      summary: Get members of a team
      description: |
        Members are sorted by reverse chronological order of joining the team (most recent first).
        OAuth only required if the list of members is private.

        Members are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Users
        - Teams
      security:
        - OAuth2: ["team:read"]
  /api/team/{teamId}/arena:
    get:
      operationId: apiTeamArena
      summary: Get team Arena tournaments
      description: |
        Get all Arena tournaments relevant to a team.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        Tournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Teams
        - "Arena tournaments"
      security: []
  /team/{teamId}/join:
    post:
      operationId: teamIdJoin
      summary: Join a team
      description: |
        Join a team.
        If the team join policy requires a confirmation but the
        `message` parameter is not given, then the call fails with
        `403 Forbidden`.
      tags:
        - Teams
      security:
        - OAuth2: ["team:write"]
  /team/{teamId}/quit:
    post:
      operationId: teamIdQuit
      summary: Leave a team
      description: |
        Leave a team.
        - <https://lishogi.org/team>
      tags:
        - Teams
      security:
        - OAuth2: ["team:write"]
  /team/{teamId}/kick/{userId}:
    post:
      operationId: teamIdKickUserId
      summary: Kick a user from your team
      description: |
        Kick a member out of one of your teams.
        - <https://lishogi.org/team>
      tags:
        - Teams
      security:
        - OAuth2: ["team:write"]
  /team/{teamId}/pm-all:
    post:
      operationId: teamIdPmAll
      summary: Message all members
      description: |
        Send a private message to all members of a team.
        You must own the team.
      tags:
        - Teams
      security:
        - OAuth2: ["team:write"]
  /streamer/live:
    get:
      operationId: streamerLive
      summary: Get live streamers
      description: |
        Get basic info about currently streaming users.

        This API is very fast and cheap on lishogi side.
        So you can call it quite often (like once every 5 seconds).
      tags:
        - Users
      security: []
  /api/crosstable/{user1}/{user2}:
    get:
      operationId: apiCrosstable
      summary: Get crosstable
      description: |
        Get total number of games, and current score, of any two users.

        If the `matchup` flag is provided, and the users are currently playing, also gets the current match game number and scores.
      tags:
        - Users
      security: []
  /api/player/autocomplete:
    get:
      operationId: apiPlayerAutocomplete
      summary: Autocomplete usernames
      description: |
        Provides autocompletion options for an incomplete username.
      tags:
        - Users
      security: []
  /api/stream/event:
    get:
      operationId: apiStreamEvent
      summary: Stream incoming events
      description: "\n
      \ Stream the events reaching a lishogi user in real time as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\n
      \ Each line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameStart` Start of a game\n
      \ - `gameFinish` Completion of a game\n
      \ - `challenge` A player sends you a challenge or you challenge someone\n
      \ - `challengeDeclined` The opponent declines your challenge\n
      \n
      \ When the stream opens, all current challenges and games are sent."
      tags:
        - Board
        - Bot
      security:
        - OAuth2: ["challenge:read", "bot:play", "board:play"]
  /api/board/seek:
    post:
      operationId: apiBoardSeek
      summary: Create a seek
      description: "\n
      \ Create a public seek, to start a game with a random player.\n\n
      \ ### Real-time seek\n\n
      \ Specify the `time`, `increment`, `byoyomi` and `periods` clock values.
      \ The response is streamed but doesn't contain any information.\n\n
      \ **Keep the connection open to keep the seek active**.\n\n
      \ If the client closes the connection, the seek is canceled. This way, if the client terminates, the user won't be paired in a game they wouldn't play.\n
      \ When the seek is accepted, or expires, the server closes the connection.\n\n
      \ **Make sure to also have an [Event stream](#operation/apiStreamEvent) open**, to be notified when a game starts.\n
      \ We recommend opening the [Event stream](#operation/apiStreamEvent) first, then the seek stream. This way,\n
      \ you won't miss the game event if the seek is accepted immediately.\n\n
      \ ### Correspondence seek\n\n
      \ Specify the `days` per turn value.
      \ The response is not streamed, it immediately completes with the seek ID. The seek remains active on the server until it is joined by someone."
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/stream/{gameId}:
    get:
      operationId: boardGameStream
      summary: Stream Board game state
      description: "\
      \ Stream the state of a game being played with the Board API, as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included. Sent when a move is played, or when the game ends.\n
      \ - `chatLine` Chat message sent by a user in the `room` \"player\" or \"spectator\".\n\n
      \nThe first line is always of type `gameFull`.\n\n
      \nThe server closes the stream when the game ends, or if the game has already ended."
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/move/{move}:
    post:
      operationId: boardGameMove
      summary: Make a Board move
      description: |
        Make a move in a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/chat:
    post:
      operationId: boardGameChatPost
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
    get:
      operationId: boardGameChatGet
      summary: Fetch the game chat
      description: |
        Get the messages posted in the game chat
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/abort:
    post:
      operationId: boardGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/resign:
    post:
      operationId: boardGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/takeback/{accept}:
    post:
      operationId: boardGameTakeback
      summary: Handle takeback offers
      description: |
        Create/accept/decline takebacks.
        - `yes`: Propose a takeback, or accept the opponent's takeback offer.
        - `no`: Decline a takeback offer from the opponent.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/bot/online:
    get:
      operationId: apiBotOnline
      summary: Get online bots
      tags:
        - Bot
      security: []
      description: Stream the [online bot users](https://lishogi.org/player/bots), as [ndjson](#section/Introduction/Streaming-with-ND-JSON). Throttled to 50 bot users per second.
  /api/bot/account/upgrade:
    post:
      operationId: botAccountUpgrade
      summary: Upgrade to Bot account
      description: |
        Upgrade a lishogi player account into a Bot account. Only Bot accounts can use the Bot API.

        The account **cannot have played any game** before becoming a Bot account. The upgrade is **irreversible**. The account will only be able to play as a Bot.

        To upgrade an account to Bot, use the [official lishogi-bot client](https://github.com/ShailChoksi/lishogi-bot), or follow these steps:
        - Create an [API access token](https://lishogi.org/account/oauth/token/create?scopes[]=bot:play) with "Play bot moves" permission.
        - `curl -d '' https://lishogi.org/api/bot/account/upgrade -H "Authorization: Bearer <yourTokenHere>"`

        To know if an account has already been upgraded, use the [Get my profile API](#operation/accountMe):
        the `title` field should be set to `BOT`.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/stream/{gameId}:
    get:
      operationId: botGameStream
      summary: Stream Bot game state
      description: "\
      \ Stream the state of a game being played with the Bot API, as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included.\n
      \ - `chatLine` Chat message sent by a user (or the bot itself) in the `room` \"player\" or \"spectator\".\n\n
      \nThe first line is always of type `gameFull`."
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/move/{move}:
    post:
      operationId: botGameMove
      summary: Make a Bot move
      description: |
        Make a move in a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/chat:
    post:
      operationId: botGameChat
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
    get:
      operationId: botGameChatGet
      summary: Fetch the game chat
      description: |
        Get the messages posted in the game chat
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/abort:
    post:
      operationId: botGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/resign:
    post:
      operationId: botGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/challenge/{username}:
    post:
      operationId: challengeCreate
      summary: Create a challenge
      description: |
        Challenge someone to play. The targeted player can choose to accept or decline.

        If the challenge is accepted, you will be notified on the [event stream](#operation/apiStreamEvent)
        that a new game has started. The game ID will be the same as the challenge ID.

        If you also have an OAuth token with `challenge:write` scope for the receiving user,
        you can make them accept the challenge immediately by setting the `acceptByToken` field.

        Challenges for realtime games (not correspondence) expire after 20s if not accepted.
        To prevent that, use the `keepAliveStream` flag described below.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/accept:
    post:
      operationId: challengeAccept
      summary: Accept a challenge
      description: |
        Accept an incoming challenge.

        You should receive a `gameStart` event on the [incoming events stream](#operation/apiStreamEvent).
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/decline:
    post:
      operationId: challengeDecline
      summary: Decline a challenge
      description: |
        Decline an incoming challenge.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/ai:
    post:
      operationId: challengeAi
      summary: Challenge the AI
      description: |
        Start a game with Lishogi AI.

        You will be notified on the [event stream](#operation/apiStreamEvent) that a new game has started.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/open:
    post:
      operationId: challengeOpen
      summary: Open-ended challenge
      description: |
        Create a challenge that any 2 players can join.

        Share the URL of the challenge. the first 2 players to click it will be paired for a game.

        The response body also contains `senteUrl` and `goteUrl`.
        You can control which color each player gets by giving them these URLs,
        instead of the main challenge URL.

        Open challenges expire after 24h.

        To directly pair 2 known players, use [this endpoint](#operation/challengeCreate) instead,
        with the `acceptByToken` parameter.
      tags:
        - Challenges
      security: []
  /inbox/{username}:
    post:
      operationId: inboxUsername
      summary: Send a private message
      description: |
        Send a private message to another player.
      tags:
        - Messaging
      security:
        - OAuth2: ["msg:write"]
  /api/cloud-eval:
    get:
      operationId: apiCloudEval
      summary: Get cloud evaluation of a position.
      description: |
        Get the cached evaluation of a position, if available.

        Opening positions have more chances of being available. There are about 500 thousand positions in the database.

        Up to 5 variations may be available. Variants are supported.
      tags:
        - Analysis
      security: []
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: |
        ### Which authentication method is right for me?
        [Read about the Lichess (Currently not made for Lishogi) API authentication methods and code examples](https://github.com/lichess-org/api/blob/master/example/README.md)

        ### Personal Access Token
        Personal API access tokens allow you to quickly interact with Lishogi API without going through an OAuth flow.
        - [Generate a personal access token](https://lishogi.org/account/oauth/token)
        - `curl https://lishogi.org/api/account -H "Authorization: Bearer {token}"`
        - [NodeJS example (for lichess)](https://github.com/lichess-org/api/tree/master/example/oauth-personal-token)

        #### Real life examples
        - [Lishogi Discord Bot](https://top.gg/bot/842330057841049600) ([source code](https://github.com/ddugovic/lishogi-discord))
        - [Lishogi Bot](https://github.com/TheYoBots/Lishogi-Bot)

        ### Token format
        Access tokens and authorization codes match `^[A-Za-z0-9_]+$`.
        The length of tokens can be increased without notice. Make sure your application can handle at least 512 characters.
        By convention tokens have a recognizable prefix, but do not rely on this.
      flows:
        authorizationCode:
          authorizationUrl: https://lishogi.org/oauth
          tokenUrl: https://lishogi.org/api/token
          scopes:
            "preference:read": Read your preferences
            "preference:write": Write your preferences
            "email:read": Read your email address
            "challenge:read": Read incoming challenges
            "challenge:write": Create, accept, decline challenges
            "study:read": Read private studies
            "study:write": Create, update and delete studies
            "tournament:write": Create tournaments
            "puzzle:read": Read puzzle activity
            "team:write": Join, leave, and manage teams
            "msg:write": Send private messages to other players
            "board:play": Play with the Board API
            "bot:play": Play with the Bot API. Only for [Bot accounts](#operation/botAccountUpgrade)
