openapi: "3.0.0"
info:
  version: 2.0.0
  title: Lishogi.org API reference
  x-logo:
    url: https://lishogi1.org/assets/logo/lishogi-pad12.svg
    backgroundColor: #ffffff
  description: "\n\n# WIP - Introduction\nWelcome to the reference for the Lishogi API! Lishogi is free/libre, open-source shogi server powered by volunteers and donations.\n\n\
  \ - This documentation is a work in progress, there is a lot of incorrect information right now - I plan to have this ready by the end of July, but no promises
  \ - Get help in the [lishogi developers discord channel](https://discord.gg/YFtpMGg3rR),\
  \ or in the #lishogi IRC channel on freenode.\n\
  \ - Check out [lishogi widgets to embed in your website](https://lishogi.org/developers).\n\
  \ - [Download all lishogi rated games](https://database.lishogi.org/)\n\
  \n## Endpoint\n\
  \ All requests go to `https://lishogi.org`.\n\
  \n## Rate limiting\n\
  \ All requests are rate limited using various strategies,\
  \ to ensure the API remains responsive for everyone.\n\
  \ Only make one request at a time.\n\
  \ If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429),\
  \ please wait a full minute before resuming API usage."
servers:
  - url: https://lishogi.org
tags:
- name: Account
  description: |
    Read and write account informations and preferences.
    https://lishogi.org/account/preferences/game-display
- name: Users
  description: |
    Access registered users on Lishogi.
    https://lishogi.org/player
- name: Relations
  description: |
    Access relations between users.
- name: Games
  description: |
    Access games played on Lishogi.
    https://lishogi.org/games
- name: Teams
  description: |
    Access and manage Lishogi teams and their members.
    https://lishogi.org/team
- name: Board
  description: "Play on Lishogi with physical boards and third-party clients.\n
  \ Works with normal Lishogi accounts. Engine play or assistance is forbidden.\n\n\
  \n### Features\n\
  \ - [Stream incoming shogi moves](#operation/boardGameStream)\n\
  \ - [Play shogi moves](#operation/boardGameMove)\n\
  \ - [Read](#operation/boardGameStream) and [write](#operation/boardGameChat) in the player and spectator chats\n\
  \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges\n\
  \ - [Abort](#operation/boardGameAbort) and [resign](#operation/boardGameResign) games\n\
  \ - Compatible with normal Lishogi accounts\n\n
  \n### Restrictions\n\
  \ - Engine assistance is strictly forbidden\n\
  \ - Casual games: [Rapid, Classical and Correspondence](https://lishogi.org/faq#time-controls) only\n\
  \ - Rated games: [Estimated duration](https://lishogi.org/faq#time-controls) >= 1200. That includes Classical, Correspondence, and some Rapid time controls such as 15+10 and 20+0.\n\
- name: Bot
  description: "Play on Lishogi as a bot. Allows engine play.\n
  \ Read the [blog post announcement of lishogi bots](https://lishogi.org/blog/WvDNticAAMu_mHKP/welcome-lishogi-bots).\n\n
  \ Only works with [Bot accounts](#operation/botAccountUpgrade).\n\n\
  \n### Features\n\
  \ - [Stream incoming shogi moves](#operation/botGameStream)\n\
  \ - [Play shogi moves](#operation/botGameMove)\n\
  \ - [Read](#operation/botGameStream) and [write](#operation/botGameChat) in the player and spectator chats\n\
  \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges\n\
  \ - [Abort](#operation/botGameAbort) and [resign](#operation/botGameResign) games\n\
  \ - Engine assistance is allowed\n\
  \n### Restrictions\n\
  \ - Bots can only play challenge games:  pools and tournaments are off-limits\n\
  \n### Integrations\n\
  \ - [Python3 lishogi-bot](https://github.com/careless25/lishogi-bot) (official)\n\
  \ - [JavaScript bot-o-tron](https://github.com/tailuge/bot-o-tron)\n\
  \ - [Golang lishogi-bot](https://github.com/dolegi/lishogi-bot)\n\
  \ - Yours? Please make [an issue or pull request](https://github.com/lishogi-org/api).\n\
  \n### Links\n\
  \ - Join the [Lishogi Bots team](https://lishogi.org/team/lishogi-bots) with your bot account\n\
  \ - [Get help in the discord channel](https://discord.gg/YFtpMGg3rR)\n\
  \ - Watch [Lishogi Bot TV](https://lishogi.org/tv/bot)"
- name: Challenges
  description: |
    Send and receive challenges to play.
- name: Arena tournaments
  description: |
    Access Arena tournaments played on Lishogi.
    [Official Arena tournaments](https://lishogi.org/tournament) are maintained by Lishogi,
    but you can [create your own Arena tournaments](https://lishogi.org/tournament/new) as well.
- name: Swiss tournaments
  description: |
    Access Swiss tournaments played on Lishogi.
    [Read more about Swiss tournaments.](https://lishogi.org/swiss).
- name: Simuls
  description: |
    Access simuls played on Lishogi.
    https://lishogi.org/simul
- name: Studies
  description: |
    Access Lishogi studies.
    https://lishogi.org/study
- name: Messaging
  description: |
    Private messages with other players.
    https://lishogi.org/inbox
- name: OAuth
  description: |
    Requests taking advantage of OAuth authentication.
    https://lishogi.org/account/oauth/app
- name: Analysis
  description: |
    Access Lishogi cloud evaluations database.
    https://lishogi.org/analysis
paths:
  /api/users/status:
    get:
      operationId: apiUsersStatus
      summary: Get real-time users status
      description: |
        Read the `online`, `playing` and `streaming` flags of several users.

        This API is very fast and cheap on lishogi side.
        So you can call it quite often (like once every 5 seconds).

        Use it to track players and know when they're connected on lishogi and playing games.
      tags:
        - Users
      security:
        - None: []
  /player:
    get:
      operationId: player
      summary: Get all top 10
      tags:
        - Users
      security:
        - SameOrigin: []
      description: |
        Get the top 10 players for each speed and variant.

        See https://lishogi.org/player.
  /player/top/{nb}/{perfType}:
    get:
      operationId: playerTopNbPerfType
      summary: Get one leaderboard
      tags:
        - Users
      security:
        - SameOrigin: []
      description: |
        Get the leaderboard for a single speed or variant (a.k.a. `perfType`).
        There is no leaderboard for correspondence or puzzles.

        See https://lishogi.org/player/top/200/bullet.
  /api/user/{username}:
    get:
      operationId: apiUser
      summary: Get user public data
      description: |
        Read public data of a user.
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/rating-history:
    get:
      operationId: apiUserRatingHistory
      summary: Get rating history of a user
      description: |
        Read rating history of a user, for all perf types.
        There is at most one entry per day.
        Format of an entry is `[year, month, day, rating]`.
        `month` starts at zero (January).
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/activity:
    get:
      operationId: apiUserActivity
      summary: Get user activity
      description: |
        Read data to generate the activity feed of a user.
      tags:
        - Users
      security:
        - None: []
  /api/user/puzzle-activity:
    get:
      operationId: apiUserPuzzleActivity
      summary: Get your puzzle activity
      description: |
        Download your puzzle activity in [ndjson](http://ndjson.org/) format.

        Puzzle activity is sorted by reverse chronological order (most recent first)

        We recommend streaming the response, for it can be very long.
      tags:
        - Users
        - OAuth
      security:
        - OAuth2: ["puzzle:read"]
  /api/users:
    post:
      operationId: apiUsers
      summary: Get users by ID
      tags:
        - Users
      security:
        - None: []
      description: |
        Get several users by their IDs. Users are returned in the order same order as the IDs.

        The method is `POST` so a longer list of IDs can be sent in the request body.
  /api/account:
    get:
      operationId: accountMe
      summary: Get my profile
      description: |
        Public informations about the logged in user.
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: []
  /api/account/email:
    get:
      operationId: accountEmail
      summary: Get my email address
      description: |
        Read the email address of the logged in user.
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["email:read"]
  /api/account/preferences:
    get:
      operationId: account
      summary: Get my preferences
      description: |
        Read the preferences of the logged in user.

        - https://lishogi.org/account/preferences/game-display
        - https://github.com/ornicar/lila/blob/master/modules/pref/src/main/Pref.scala
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:read"]
  /api/account/kid:
    get:
      operationId: accountKid
      summary: Get my kid mode status
      description: |
        Read the kid mode status of the logged in user.

        - https://lishogi.org/account/kid
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:read"]
    post:
      operationId: accountKidPost
      summary: Set my kid mode status
      description: |
        Set the kid mode status of the logged in user.

        - https://lishogi.org/account/kid
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:write"]
  /game/export/{gameId}:
    get:
      operationId: gameNotation
      summary: Export one game
      description: |
        Download one game in either KIF, CSA or JSON format.
        If the game is ongoing, the 3 last moves are omitted.
      tags:
        - Games
      security:
        - None: []
  /api/user/{username}/current-game:
    get:
      operationId: apiUserCurrentGame
      summary: Export ongoing game of a user
      description: |
        Download the ongoing game, or the last game played, of a user.
        Available in either KIF, CSA or JSON format.
        If the game is ongoing, the 3 last moves are omitted.
      tags:
        - Games
      security:
        - None: []
  /api/games/user/{username}:
    get:
      operationId: apiGamesUser
      summary: Export games of a user
      description: |
        Download all games of any user in KIF, CSA or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (most recent first)

        We recommend streaming the response, for it can be very long.

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Authentication) request: 30 games per second
          - Authenticated, downloading your own games: 60 games per second
      tags:
        - Games
        - OAuth
      security:
        - None: []
  /games/export/_ids:
    post:
      operationId: gamesExportIds
      summary: Export games by IDs
      description: |
        Download games by IDs in KIF, CSA or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (most recent first)

        The method is `POST` so a longer list of IDs can be sent in the request body.

        300 IDs can be submitted. If the request uses OAuth2, 500 IDs can be submitted.
      tags:
        - Games
      security:
        - SameOrigin: []
  /api/stream/games-by-users:
    post:
      operationId: gamesByUsers
      summary: Stream current games
      description: |
        Stream the games played between a list of users, in real time.
        Only games where **both players** are part of the list are included.

        Maximum number of users: 300.

        **Games are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.

        The method is `POST` so a longer list of IDs can be sent in the request body.
      tags:
        - Games
      security:
        - None: []
  /api/account/playing:
    get:
      operationId: apiAccountPlaying
      summary: Get ongoing games
      description: |
        Get the ongoing games of the current user.
        Real-time and correspondence games are included.
        The most urgent games are listed first.
      tags:
        - Games
        - OAuth
      security:
        - OAuth2: []
  /tv/channels:
    get:
      operationId: tvChannels
      summary: Get current TV games
      description: |
        Get basic info about the best games being played for each speed and variant,
        but also computer games and bot games.

        See [lishogi.org/tv](https://lishogi.org/tv).
      tags:
        - Games
      security:
        - SameOrigin: []
  /api/tournament:
    get:
      operationId: apiTournament
      summary: Get current tournaments
      description: |
        Get recently finished, ongoing, and upcoming tournaments.

        This API is used to display the [Lishogi tournament schedule](https://lishogi.org/tournament).
      tags:
        - "Arena tournaments"
      security:
        - None: []
    post:
      operationId: apiTournamentPost
      summary: Create a new Arena tournament
      description: |
        Create a public or private Arena tournament.

        This endpoint mirrors the form on https://lishogi.org/tournament/new.

        You can create up to 12 public tournaments per day, or 24 private tournaments.
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}:
    get:
      operationId: tournament
      summary: Get info about a tournament
      description: |
        Get detailed info about recently finished, current, or upcoming tournament's duels, player standings, and other info.
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/games:
    get:
      operationId: gamesByTournament
      summary: Export games of an Arena tournament
      description: |
        Download games of a tournament in KIF, CSA or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (most recent first)
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/results:
    get:
      operationId: resultsByTournament
      summary: Get results of a tournament
      description: |
        Players of a tournament, with their score and performance, sorted by rank (best first).

        **Players are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/teams:
    get:
      operationId: teamsByTournament
      summary: Get team standing of a team battle
      description: |
        Teams of a team battle tournament, with top players, sorted by rank (best first).
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/user/{username}/tournament/created:
    get:
      operationId: apiUserNameTournamentCreated
      summary: Get tournaments created by a user
      description: |
        Get all tournaments created by a given user.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        **Tournaments are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/swiss/new/{teamId}:
    post:
      operationId: apiSwissNew
      summary: Create a new Swiss tournament
      description: |
        Create a Swiss tournament for your team.

        This endpoint mirrors the Swiss tournament form from your team pagee.

        You can create up to 12 tournaments per day.
      tags:
        - "Swiss tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /swiss/{id}.trf:
    get:
      operationId: swissTrf
      summary: Export TRF of a Swiss tournament
      description: |
        Download a tournament in the Tournament Report File format, the FIDE standard.

        Documentation: https://www.fide.com/FIDE/handbook/C04Annex2_TRF16.pdf

        Example: https://lishogi.org/swiss/j8rtJ5GL.trf
      tags:
        - "Swiss tournaments"
      security:
        - None: []
  /api/swiss/{id}/games:
    get:
      operationId: gamesBySwiss
      summary: Export games of a Swiss tournament
      description: |
        Download games of a tournament in KIF, CSA or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (last round first)
      tags:
        - "Swiss tournaments"
      security:
        - None: []
  /study/{studyId}/{chapterId}.kif:
    get:
      operationId: studyChapterKif
      summary: Export one study chapter
      description: |
        Download one study chapter in KIF format.
      tags:
        - Studies
      security:
        - SameOrigin: []
  /study/{studyId}.kif:
    get:
      operationId: studyChapterKif
      summary: Export all chapters
      description: |
        Download all chapters of a study in KIF format.
      tags:
        - Studies
      security:
        - SameOrigin: []
  /api/simul:
    get:
      operationId: apiSimul
      summary: Get current simuls
      description: |
        Get recently finished, ongoing, and upcoming simuls.
      tags:
        - Simuls
      security:
        - None: []
  /api/team/{teamId}:
    get:
      operationId: teamShow
      summary: Get a single team
      description: Infos about a team
      tags:
        - Teams
      security:
        - None: []
  /api/team/all:
    get:
      operationId: teamAll
      summary: Get popular teams
      description: |
        Paginator of the most popular teams.
      tags:
        - Teams
      security:
        - None: []
  /api/team/of/{username}:
    get:
      operationId: teamOfUsername
      summary: Teams of a player
      description: |
        All the teams a player is a member of.
      tags:
        - Teams
      security:
        - None: []
  /api/team/search:
    get:
      operationId: teamSearch
      summary: Search teams
      description: |
        Paginator of team search results for a keyword.
      tags:
        - Teams
      security:
        - None: []
  /api/team/{teamId}/users:
    get:
      operationId: teamIdUsers
      summary: Get members of a team
      description: |
        Members are sorted by reverse chronological order of joining the team (most recent first).

        **Members are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Users
        - Teams
      security:
        - None: []
  /api/team/{teamId}/arena:
    get:
      operationId: apiTeamArena
      summary: Get team arena tournaments
      description: |
        Get all tournaments relevant to a team.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        **Tournaments are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Teams
        - "Arena tournaments"
      security:
        - None: []
  /team/{teamId}/join:
    post:
      operationId: teamIdJoin
      summary: Join a team
      description: |
        Join a team.
        If the team join policy requires a confirmation,
        and the team owner is not the oAuth app owner,
        and the `message` field is not set,
        then the call fails with `403 Forbidden`.
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/quit:
    post:
      operationId: teamIdQuit
      summary: Leave a team
      description: |
        Leave a team.
        - https://lishogi.org/team
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/kick/{userId}:
    post:
      operationId: teamIdKickUserId
      summary: Kick a user from your team
      description: |
        Kick a member out of one of your teams.
        - https://lishogi.org/team
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/pm-all:
    post:
      operationId: teamIdPmAll
      summary: Message all members
      description: |
        Send a private message to all members of a team.
        You must own the team.
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
  /streamer/live:
    get:
      operationId: streamerLive
      summary: Get live streamers
      description: |
        Get basic info about currently streaming users.

        This API is very fast and cheap on lishogi side.
        So you can call it quite often (like once every 5 seconds).
      tags:
        - Users
      security:
        - None: []
          SameOrigin: []
  /api/user/{username}/following:
    get:
      operationId: apiUserFollowing
      summary: Get users followed by a user
      description: |
        **Users are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Relations
      security:
        - None: []
  /api/user/{username}/followers:
    get:
      operationId: apiUserFollowers
      summary: Get users who follow a user
      description: |
        **Users are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Relations
      security:
        - None: []
  /api/stream/event:
    get:
      operationId: apiStreamEvent
      summary: Stream incoming events
      description: "\n
      \ Stream the events reaching a lishogi user in real time as [ndjson](http://ndjson.org/).\n\n
      \ Each line is a JSON object containing a `type` field. Possible values are:\n
      \ - `challenge` Incoming challenge\n
      \ - `gameStart` Start of a game\n\n
      \n
      \ When the stream opens, all current challenges and games are sent."
      tags:
        - Board
        - Bot
        - Challenges
      security:
        - OAuth2: ["challenge:read", "bot:play", "board:play"]
  /api/board/seek:
    post:
      operationId: apiBoardSeek
      summary: Create a seek
      description: "\n
      \ Create a public seek, to start a game with a random player.\n\n
      \ The response is streamed but doesn't contain any information. **Keep the connection open to keep the seek active**.\n\n
      \ If the client closes the connection, the seek is canceled.\n\n
      \ If the seek is accepted, or expires, the server closes the connection.\n\n
      \ **Make sure to also have an [Event stream](#operation/apiStreamEvent) open**, to be notified when a game starts.\n
      \ We recommend opening the [Event stream](#operation/apiStreamEvent) first, then the seek stream. This way,\n
      \ you won't miss the game event if the seek is accepted immediately."
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/stream/{gameId}:
    get:
      operationId: boardGameStream
      summary: Stream Board game state
      description: "\
      \ Stream the state of a game being played with the Board API, as [ndjson](http://ndjson.org/).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included. Sent when a move is played, a draw is offered, or when the game ends.\n
      \ - `chatLine` Chat message sent by a user in the `room` \"player\" or \"spectator\".\n\n
      \nThe first line is always of type `gameFull`."
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/move/{move}:
    post:
      operationId: boardGameMove
      summary: Make a Board move
      description: |
        Make a move in a game being played with the Board API.

        The move can also contain a draw offer/agreement.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/chat:
    post:
      operationId: boardGameChat
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/abort:
    post:
      operationId: boardGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/resign:
    post:
      operationId: boardGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/draw/{accept}:
    post:
      operationId: boardGameDraw
      summary: Handle draw offers
      description: |
        Create/accept/decline draw offers.
        - `yes`: Offer a draw, or accept the opponent's draw offer.
        - `no`: Decline a draw offer from the opponent.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/bot/account/upgrade:
    post:
      operationId: botAccountUpgrade
      summary: Upgrade to Bot account
      description: |
        Upgrade a lishogi player account into a Bot account. Only Bot accounts can use the Bot API.

        The account **cannot have played any game** before becoming a Bot account. The upgrade is **irreversible**. The account will only be able to play as a Bot.

        Follow these steps:
        - Create an [API access token](https://lishogi.org/account/oauth/token/create?scopes[]=bot:play) with "Play bot moves" permission.
        - `curl -d '' https://lishogi.org/api/bot/account/upgrade -H "Authorization: Bearer <yourTokenHere>"`

        To know if an account has already been upgraded, use the [Get my profile API](#operation/accountMe):
        the `title` field should be set to `BOT`.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/stream/{gameId}:
    get:
      operationId: botGameStream
      summary: Stream Bot game state
      description: "\
      \ Stream the state of a game being played with the Bot API, as [ndjson](http://ndjson.org/).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included.\n
      \ - `chatLine` Chat message sent by a user (or the bot itself) in the `room` \"player\" or \"spectator\".\n\n
      \nThe first line is always of type `gameFull`."
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/move/{move}:
    post:
      operationId: botGameMove
      summary: Make a Bot move
      description: |
        Make a move in a game being played with the Bot API.

        The move can also contain a draw offer/agreement.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/chat:
    post:
      operationId: botGameChat
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/abort:
    post:
      operationId: botGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/resign:
    post:
      operationId: botGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/challenge/{username}:
    post:
      operationId: challengeCreate
      summary: Create a challenge
      description: |
        Challenge someone to play. The targeted player can choose to accept or decline.

        If the challenge is accepted, you will be notified on the [event stream](#operation/apiStreamEvent)
        that a new game has started. The game ID will be the same as the challenge ID.

        If you also have an OAuth token with `challenge:write` scope for the receiving user,
        you can make them accept the challenge immediately by setting the `acceptByToken` field.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/accept:
    post:
      operationId: challengeAccept
      summary: Accept a challenge
      description: |
        Accept an incoming challenge.

        You should receive a `gameStart` event on the [incoming events stream](#operation/apiStreamEvent).
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/decline:
    post:
      operationId: challengeDecline
      summary: Decline a challenge
      description: |
        Decline an incoming challenge.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/ai:
    post:
      operationId: challengeAi
      summary: Challenge the AI
      description: |
        Start a game with Lishogi AI.

        You will be notified on the [event stream](#operation/apiStreamEvent) that a new game has started.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/open:
    post:
      operationId: challengeOpen
      summary: Open-ended challenge
      description: |
        Create a challenge that any 2 players can join.

        Share the URL of the challenge. the first 2 players to click it will be paired for a game.

        The response body also contains `whiteUrl` and `blackUrl`.
        You can control which color each player gets by giving them these URLs,
        instead of the main challenge URL.

        Open challenges expire after 24h.

        To directly pair 2 known players, use [this endpoint](#operation/challengeCreate) instead,
        with the `acceptByToken` parameter.
      tags:
        - Challenges
      security:
        - None: []
  /inbox/{username}:
    post:
      operationId: inboxUsername
      summary: Send a private message
      description: |
        Send a private message to another player.
      tags:
        - Messaging
      security:
        - OAuth2: ["msg:write"]
          SameOrigin: []
  /api/cloud-eval:
    get:
      operationId: apiCloudEval
      summary: Get cloud evaluation of a position.
      description: |
        Get the cached evaluation of a position, if available.

        Opening positions have more chances of being available.

        Up to 5 variations may be available. Variants are supported.
      tags:
        - Analysis
      security:
        - None: []
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: "### Authorization Code Flow\n\
        \ The authorization code flow allows your users to **login with lishogi**.\n\
        \ - [Create a Lishogi OAuth app](https://lishogi.org/account/oauth/app)\n\
        \ - [About authorization code flow](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2#grant-type-authorization-code)\n\
        \n### Personal API Token\n\
        \ Personal API tokens allow you to quickly interact with Lishogi OAuth API.\n\
        \ - `curl https://lishogi.org/api/account -H \"Authorization: Bearer <token>\"`\n\
        \ - [Generate a personal API token](https://lishogi.org/account/oauth/token)"
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.lishogi.org/oauth/authorize
          tokenUrl: https://oauth.lishogi.org/oauth
          scopes:
            "preference:read": Read your preferences
            "preference:write": Write your preferences
            "email:read": Read your email address
            "challenge:read": Read incoming challenges
            "challenge:write": Create, accept, decline challenges
            "tournament:write": Create tournaments
            "board:play": Play with the Board API
            "bot:play": Play with the Bot API. Only for [Bot accounts](#operation/botAccountUpgrade)
    SameOrigin:
      description: "CORS is not supported on this endpoint.\n\
        \ If you need it, please\n\
        \ [make an issue](https://github.com/ornicar/lila/issues/new)\n\
        \ to request it."
      type: none
    None:
      description: "No authorization required.\n\
        \ For requests that don't need an authenticated user."
      type: none