package lila.socket

import play.api.libs.json.*

object Socket extends Socket:

  // Socket Random Id - an unique identifier for a socket connection
  // Generated by clients when initiating a connection:
  // https://github.com/lichess-org/lila/blob/master/ui/site/src/component/sri.ts#L3-L6
  opaque type Sri = String
  object Sri extends OpaqueString[Sri]

  case class Sris(sris: Set[Sri]) // pattern matched

private[socket] trait Socket:

  def makeMessage[A](t: String, data: A)(using writes: Writes[A]): JsObject =
    JsObject(Map.Map2("t", JsString(t), "d", writes.writes(data)))

  def makeMessage(t: String): JsObject = JsObject(Map.Map1("t", JsString(t)))
