package lila.quote

case class Quote(text: String, author: String)

object Quotes {

  // courtesy of http://www.chess-poster.com/english/notes_and_facts/chess_quotes.htm
  val all = Vector(
    Quote("When you see a good move, look for a better one", "Emanuel Lasker"),
    Quote("Nothing excites jaded Grandmasters more than a theoretical novelty", "Dominic Lawson"),
    Quote("The Pin is mightier than the sword", "Fred Reinfeld"),
    Quote("We cannot resist the fascination of sacrifice, since a passion for sacrifices is part of a Chessplayer’s nature", "Rudolf Spielman"),
    Quote("All I want to do, ever, is just play Chess", "Bobby Fischer"),
    Quote("A win by an unsound combination, however showy, fills me with artistic horror", "Wilhelm Steinitz"),
    Quote("The chessboard is the world, the pieces are the phenomena of the Universe, the rules of the game are what we call the laws of Nature and the player on the other side is hidden from us", "Thomas Huxley"),
    Quote("Adequate compensation for a sacrifice is having a sound combination leading to a winning position; adequate compensation for a blunder is having your opponent snatch defeat from the jaws of victory", "Bruce A. Moon"),
    Quote("Strategy requires thought, tactics require observation", "Max Euwe"),
    Quote("I don’t believe in psychology. I believe in good moves", "Bobby Fischer"),
    Quote("Modern Chess is too much concerned with things like Pawn structure. Forget it, Checkmate ends the game", "Nigel Short"),
    Quote("Life is a kind of Chess, with struggle, competition, good and ill events", "Benjamin Franklin"),
    Quote("Even the laziest King flees wildly in the face of a double check!", "Aaron Nimzowitsch"),
    Quote("Combinations have always been the most intriguing aspect of Chess.  The masters look for them, the public applauds them, the critics praise them. It is because combinations are possible that Chess is more than a lifeless mathematical exercise. They are the poetry of the game; they are to Chess what melody is to music. They represent the triumph of mind over matter", "Reuben Fine"),
    Quote("I give 98 percent of my mental energy to Chess", "Bobby Fischer"),
    Quote("Chess is a fairy tale of 1001 blunders", "Savielly Tartakower"),
    Quote("Chess is no whit inferior to the violin, and we have a large number of professional violinists", "Mikhail Botvinnik"),
    Quote("Only the player with the initiative has the right to attack", "Wilhelm Steinitz"),
    Quote("The winner of the game is the player who makes the next-to-last mistake", "Savielly Tartakover"),
    Quote("Your body has to be in top condition. Your Chess deteriorates as your body does. You can’t separate body from mind", "Bobby Fischer"),
    Quote("Of Chess it has been said that life is not long enough for it, but that is the fault of life, not Chess", "William Ewart Napier"),
    Quote("I have added these principles to the law: get the Knights into action before both Bishops are developed", "Emanuel Lasker"),
    Quote("Life is like a game of Chess, changing with each move", "Chinese proverb"),
    Quote("You cannot play at Chess if you are kind-hearted", "French Proverb"),
    Quote("Its just you and your opponent at the board and you’re trying to prove something", "Bobby Fischer"),
    Quote("It is the aim of the modern school, not to treat every position according to one general law, but according to the principle inherent in the position", "Richard Reti"),
    Quote("The Pawns are the soul of the game", "Francois Andre Danican Philidor"),
    Quote("In order to improve your game, you must study the endgame before everything else, for whereas the endings can be studied and mastered by themselves, the middle game and the opening must be studied in relation to the endgame", "Jose Raul Capablanca"),
    Quote("Without error there can be no brilliancy", "Emanuel Lasker"),
    Quote("Chess is like war on a board", "Bobby Fischer"),
    Quote("Chess is played with the mind and not with the hands!", "Renaud and Kahn"),
    Quote("Chess is mental torture", "Garry Kasparov"),
    Quote("Many have become Chess Masters, no one has become the Master of Chess", "Siegbert Tarrasch"),
    Quote("The most important feature of the Chess position is the activity of the pieces. This is absolutely fundamental in all phases of the game: Opening, Middlegame and especially Endgame. The primary constraint on a piece’s activity is the Pawn structure", "Michael Stean"),
    Quote("You have to have the fighting spirit. You have to force moves and take chances", "Bobby Fischer"),
    Quote("Could we look into the head of a Chess player, we should see there a whole world of feelings, images, ideas, emotion and passion", "Alfred Binet"),
    Quote("Openings teach you openings. Endgames teach you chess!", "Stephan Gerzadowicz"),
    Quote("My style is somewhere between that of Tal and Petrosian", "Reshevsky"),
    Quote("Play the opening like a book, the middle game like a magician, and the endgame like a machine", "Spielmann"),
    Quote("That’s what Chess is all about. One day you give your opponent a lesson, the next day he gives you one", "Bobby Fischer"),
    Quote("Some part of a mistake is always correct", "Savielly Tartakover"),
    Quote("Methodical thinking is of more use in Chess than inspiration", "C. J. S. Purdy"),
    Quote("When in doubt... play Chess!", "Tevis"),
    Quote("Who is your opponent tonight, tonight I am playing against the Black pieces", "Akiba Rubinstein"),
    Quote("I like the moment when I break a man’s ego", "Bobby Fischer"),
    Quote("Excellence at Chess is one mark of a scheming mind", "Sir Arthur Conan Doyle"),
    Quote("A bad day of Chess is better than any good day at work", "Anonymous"),
    Quote("Chess is the art of analysis", "Mikhail Botvinnik"),
    Quote("The mistakes are there, waiting to be made", "Savielly Tartakower"),
    Quote("There are tough players and nice guys, and I’m a tough player", "Bobby Fischer"),
    Quote("After black’s reply to 1.e4 with 1..e5, leaves him always trying to get into the game", "Howard Staunton"),
    Quote("A player surprised is half beaten", "Proverb"),
    Quote("A passed Pawn increases in strength as the number of pieces on the board diminishes", "Capablanca"),
    Quote("The essence of Chess is thinking about what Chess is", "David Bronstein"),
    Quote("I am the best player in the world and I am here to prove it", "Bobby Fischer"),
    Quote("Chess is a forcing house where the fruits of character can ripen more fully than in life", "Edward Morgan Foster"),
    Quote("Half the variations which are calculated in a tournament game turn out to be completely superfluous. Unfortunately, no one knows in advance which half", "Jan Tinman"),
    Quote("Chess is as much a mystery as women", "Purdy"),
    Quote("Good positions don’t win games, good moves do", "Gerald Abrahams"),
    Quote("If I win a tournament, I win it by myself.  I do the playing. Nobody helps me", "Bobby Fischer"),
    Quote("What would Chess be without silly mistakes?", "Kurt Richter"),
    Quote("Before the endgame, the Gods have placed the middle game", "Siegbert Tarrasch"),
    Quote("Chess was Capablanca’s mother tongue", "Reti"),
    Quote("Alekhine is a poet who creates a work of art out of something that would hardly inspire another man to send home a picture post card", "Max Euwe"),
    Quote("Don’t even mention losing to me. I can’t stand to think of it", "Bobby Fischer"),
    Quote("During a Chess competition a Chessmaster should be a combination of a beast of prey and a monk", "Alexander Alekhine"),
    Quote("No one ever won a game by resigning", "Saviely Tartakower"),
    Quote("The defensive power of a pinned piece is only imaginary", "Aaron Nimzovich"),
    Quote("When the Chess game is over, the Pawn and the King go back to the same box", "Irish saying"),
    Quote("A strong memory, concentration, imagination, and a strong will is required to become a great Chess player", "Bobby Fischer"),
    Quote("Every Chess master was once a beginner", "Chernev"),
    Quote("One doesn’t have to play well, it’s enough to play better than your opponent", "Siegbert Tarrasch"),
    Quote("Chess is above all, a fight!", "Emanuel Lasker"),
    Quote("Discovered check is the dive bomber of the Chessboard", "Reuben Fine"),
    Quote("I know people who have all the will in the world, but still can’t play good Chess", "Bobby Fischer"),
    Quote("A Chess game is a dialogue, a conversation between a player and his opponent. Each move by the opponent may contain threats or be a blunder, but a player cannot defend against threats or take advantage of blunders if he does not first ask himself: What is my opponent planning after each move?", "Bruce A. Moon"),
    Quote("The hardest game to win is a won game", "Emanuel Lasker"),
    Quote("The most powerful weapon in Chess is to have the next move", "David Bronstein"),
    Quote("He who fears an isolated Queen’s Pawn should give up Chess", "Siegbert Tarrasch"),
    Quote("Different people feel differently about resigning", "Bobby Fischer"),
    Quote("Chess is not like life... it has rules!", "Mark Pasternak"),
    Quote("Why must I lose to this idiot?", "Aron Nimzovich"),
    Quote("It’s always better to sacrifice your opponent’s men", "Savielly Tartakover"),
    Quote("To avoid losing a piece, many a person has lost the game", "Savielly Tartakover"),
    Quote("All that matters on the Chessboard is good moves", "Bobby Fischer"),
    Quote("Help your pieces so they can help you", "Paul Morphy"),
    Quote("In a gambit you give up a Pawn for the sake of getting a lost game", "Samuel Standige Boden"),
    Quote("It is not enough to be a good player... you must also play well", "Siegbert Tarrasch"),
    Quote("A sacrifice is best refuted by accepting it", "Wilhelm Steinitz"),
    Quote("Tactics flow from a superior position", "Bobby Fischer"),
    Quote("Later, I began to succeed in decisive games. Perhaps because I realized a very simple truth: not only was I worried, but also my opponent", "Mikhail Tal"),
    Quote("Chess is life", "Bobby Fischer"),
    Quote("Chess is a beautiful mistress", "Bent Larsen"),
    Quote("Some sacrifices are sound; the rest are mine", "Mikhail Tal"),
    Quote("Best by test: 1. e4", "Bobby Fischer"),
    Quote("A bad plan is better than none at all", "Frank Marshall"),
    Quote("Chess books should be used as we use glasses: to assist the sight, although some players make use of them as if they thought they conferred sight", "Jose Raul Capablanca"),
    Quote("There are two types of sacrifices: correct ones and mine", "Mikhail Tal"),
    Quote("Morphy was probably the greatest genius of them all", "Bobby Fischer"),
    Quote("My opponents make good moves too. Sometimes I don’t take these things into consideration", "Bobby Fischer"),
    Quote("The combination player thinks forward; he starts from the given position, and tries the forceful moves in his mind", "Emanuel Lasker"),
    Quote("A Chess game is divided into three stages: the first, when you hope you have the advantage, the second when you believe you have an advantage, and the third... when you know you’re going to lose!", "Savielly Tartakower"),
    Quote("Chess demands total concentration", "Bobby Fischer"),
    Quote("Chess, like love, like music, has the power to make people happy", "Siegbert Tarrasch"),
    Quote("All my games are real", "Bobby Fischer"),
    Quote("Chess is everything: art, science and sport", "Anatoly Karpov"),
    Quote("Chess is the art which expresses the science of logic", "Mikhail Botvinnik"),
    Quote("Not all artists are Chess players, but all Chess players are artists", "Marcel Duchamp"),
    Quote("Chess is imagination", "David Bronstein"),
    Quote("I’m not afraid of Spassky. The world knows I’m the best", "Bobby Fischer"),
    Quote("If cunning alone were needed to excel, women", "Albin"),
    Quote("Chess is thirty to forty percent psychology. You don’t have this when you play a computer. I can’t confuse it", "Judith Polgar"),
    Quote("On the chessboard, lies and hypocrisy do not survive long", "Emanuel Lasker"),
    Quote("Chess is war over the board. The object is to crush the opponents mind", "Bobby Fischer"),
    Quote("The passed Pawn is a criminal, who should be kept under lock and key.  Mild measures, such as police surveillance, are not sufficient", "Aaron Nimzovich"),
    Quote("Chess holds its master in its own bonds, shackling the mind and brain so that the inner freedom of the very strongest must suffer", "Albert Einstein"),
    Quote("Human affairs are like a Chess game: only those who do not take it seriously can be called good players", "Hung Tzu Ch’eng"),
    Quote("The blunders are all there on the board, waiting to be made", "Savielly Tartakover"),
    Quote("Via the squares on the chessboard, the Indians explain the movement of time and the age, the higher influences which control the world and the ties which link Chess with the human soul", "Al-Masudi"),
    Quote("It is no time to be playing Chess when the house is on fire", "Italian Proverb"),
    Quote("You sit at the board and suddenly your heart leaps. Your hand trembles to pick up the piece and move it.  But what Chess teaches you is that you must sit there calmly and think about whether its really a good idea and whether there are other better ideas", "Stanley Kubrick"),
    Quote("Daring ideas are like Chess men moved forward. They may be beaten, but they may start a winning game", "Johann Wolfgang von Goethe"),
    Quote("Of all my Russian books, the defense contains and diffuses the greatest ’warmth’ which may seem odd seeing how supremely abstract Chess is supposed to be", "Vladimir Nabokov"),
    Quote("For surely of all the drugs in the world, Chess must be the most permanently pleasurable", "Assiac"),
    Quote("A thorough understanding of the typical mating continuations makes the most complicated sacrificial combinations leading up to them not only not difficult, but almost a matter of course", "Siegbert Tarrasch"),
    Quote("Chess problems demand from the composer the same virtues that characterize all worthwhile art: originality, invention, conciseness, harmony, complexity, and splendid insincerity", "Vladimir Nabokov"), Quote("Personally, I rather look forward to a computer program winning the world Chess Championship. Humanity needs a lesson in humility", "Richard Dawkings"),
    Quote("The boy (then a 12 year old boy named Anatoly Karpov) doesn’t have a clue about Chess, and there’s no future at all for him in this profession", "Mikhail Botvinnik"),
    Quote("As one by one I mowed them down, my superiority soon became apparent", "Jose Capablanca"),
    Quote("Though most people love to look at the games of the great attacking masters, some of the most successful players in history have been the quiet positional players. They slowly grind you down by taking away your space, tying up your pieces, and leaving you with virtually nothing to do!", "Yasser Seirawan"),
    Quote("Chess is ruthless: you’ve got to be prepared to kill people", "Nigel Short"),
    Quote("There must have been a time when men were demigods, or they could not have invented Chess", "Gustav Schenk"),
    Quote("Chess is really ninety nine percent calculation", "Soltis"),
    Quote("Chess is the gymnasium of the mind", "Blaise Pascal"),
    Quote("The game of Chess is not merely an idle amusement; several very valuable qualities of the mind are to be acquired and strengthened by it, so as to become habits ready on all occasions; for life is a kind of Chess", "Benjamin Franklin"),
    Quote("Winning isn’t everything... but losing is nothing", "Mednis"),
    Quote("Only sissies Castle", "Rob Sillars"),
    Quote("Look at Garry Kasparov. After he loses, invariably he wins the next game. He just kills the next guy. That’s something that we have to learn to be able to do", "Maurice Ashley"),
    Quote("There just isn’t enough televised Chess ", "David Letterman"),
    Quote("Avoid the crowd. Do your own thinking independently.  Be the Chess player, not the Chess piece", "Ralph Charell"),
    Quote("Chess is a terrible game. If you have no center, your opponent has a freer position. If you do have a center, then you really have something to worry about!", "Siegbert Tarrasch"),
    Quote("Any material change in a position must come about by mate, a capture, or a Pawn promotion", "Purdy"),
    Quote("We don’t really know how the game was invented, though there are suspicions. As soon as we discover the culprits, we’ll let you know", "Bruce Pandolfini"),
    Quote("The battle for the ultimate truth will never be won.  And that’s why Chess is so fascinating", "Hans Kmoch"),
    Quote("Chess makes man wiser and clear-sighted", "Vladimir Putin"),
    Quote("I am still a victim of Chess. It has all the beauty of art and much more. It cannot be commercialized. Chess is much purer than art in its social position", "Marcel Duchamp"),
    Quote("Blessed be the memory of him who gave the world this immortal game", "A. G. Gardiner"),
    Quote("In the perfect Chess combination as in a first-rate short story, the whole plot and counter-plot should lead up to a striking finale, the interest not being allayed until the very last moment", "Yates and Winter"),
    Quote("Castle early and often", "Rob Sillars"),
    Quote("I believe that Chess possesses a magic that is also a help in advanced age. A rheumatic knee is forgotten during a game of Chess and other events can seem quite unimportant in comparison with a catastrophe on the chessboard", "Vlastimil Hort"), Quote("Chess is a more highly symbolic game, but the aggressions are therefore even more frankly represented in the play. It probably began as a war game; that is, the representation of a miniature battle between the forces of two kingdoms", "Karl Meninger"),
    Quote("No Chess Grandmaster is normal; they only differ in the extent of their madness", "Viktor Korchnoi"),
    Quote("Chess is 99 percent tactics", "Teichmann"),
    Quote("I’d rather have a Pawn than a finger", "Reuben Fine"),
    Quote("Chess mastery essentially consists of analyzing", "Mikhail Botvinnik"),
    Quote("If your opponent cannot do anything active, then don’t rush the position; instead you should let him sit there, suffer, and beg you for a draw", "Jeremy Silman"),
    Quote("The Chess pieces are the block alphabet which shapes thoughts; and these thoughts, although making a visual design on the chessboard, express their beauty abstractly, like a poem", "Marcel Duchamp"),
    Quote("Examine moves that smite! A good eye for smites is far more important than a knowledge of strategical principles", "Purdy"),
    Quote("Chess is like life", "Boris Spassky"),
    Quote("If your opponent offers you a draw, try to work out why he thinks he’s worse off", "Nigel Short"),
    Quote("Chess teaches you to control the initial excitement you feel when you see something that looks good and it trains you to think objectively when you’re in trouble", "Stanley Kubrick"),
    Quote("Let the perfectionist play postal", "Yasser Seirawan"),
    Quote("If Chess is a science, it’s a most inexact one. If Chess is an art, it is too exacting to be seen as one. If Chess is a sport, it’s too esoteric. If Chess is a game, it’s too demanding to be just a game. If Chess is a mistress, she’s a demanding one. If Chess is a passion, it’s a rewarding one. If Chess is life, it’s a sad one", "Unknown"),
    Quote("Chess is a foolish expedient for making idle people believe they are doing something very clever when they are only wasting their time", "George Bernard Shaw"),
    Quote("You must take your opponent into a deep dark forest where 2+2=5, and the path leading out is only wide enough for one", "Mikhail Tal"),
    Quote("I feel as if I were a piece in a game of Chess, when my opponent says of it: That piece cannot be moved", "Soren Kierkegaard"),
    Quote("When your house is on fire, you cant be bothered with the neighbors.  Or, as we say in Chess, if your King is under attack you don’t worry about losing a Pawn on the Queen’s side", "Gary Kasparov"),
    Quote("Man is a frivolous, a specious creature, and like a Chess player, cares more for the process of attaining his goal than for the goal itself", "Dostoyevsky"),
    Quote("When asked, -How is that you pick better moves than your opponents?, I responded: I’m very glad you asked me that, because, as it happens, there is a very simple answer. I think up my own moves, and I make my opponent think up his", "Alexander Alekhine"),
    Quote("Mistrust is the most necessary characteristic of the Chess player", "Siegbert Tarrasch"), Quote("What is the object of playing a gambit opening?... To acquire a reputation of being a dashing player at the cost of losing a game", "Siegbert Tarrasch"),
    Quote("Pawns: they are the soul of this game, they alone form the attack and defense", "Philidor"),
    Quote("Chess is above all, a fight!", "Emanuel Lasker"),
    Quote("In Chess, at least, the brave inherit the earth", "Edmar Mednis"),
    Quote("There are two classes of men; those who are content to yield to circumstances and who play whist; those who aim to control circumstances, and who play Chess", "Mortimer Collins"),
    Quote("The tactician must know what to do whenever something needs doing; the strategist must know what to do when nothing needs doing", "Savielly Tartakover"),
    Quote("When you are lonely, when you feel yourself an alien in the world, play Chess. This will raise your spirits and be your counselor in war", "Aristotle"),
    Quote("All Chess players should have a hobby", "Savielly Tartakower"),
    Quote("I played Chess with him and would have beaten him sometimes only he always took back his last move, and ran the game out differently", "Mark Twain"),
    Quote("The tactician knows what to do when there is something to do; whereas the strategian knows what to do when there is nothing to do", "Gerald Abrahams"),
    Quote("In Chess, just as in life, today’s bliss may be tomorrow’s poison", "Assaic"),
    Quote("You may learn much more from a game you lose than from a game you win. You will have to lose hundreds of games before becoming a good player", "Jose Raul Capablanca"),
    Quote("The way he plays Chess demonstrates a man’s whole nature", "Stanley Ellin"),
    Quote("You can only get good at Chess if you love the game", "Bobby Fischer"),
    Quote("A man that will take back a move at Chess will pick a pocket", "Richard Fenton"),
    Quote("Whoever sees no other aim in the game than that of giving checkmate to one’s opponent will never become a good Chess player", "Euwe"),
    Quote("In blitz, the Knight is stronger than the Bishop", "Vlastimil Hort"),
    Quote("Chess is a fighting game which is purely intellectual and includes chance", "Richard Reti"),
    Quote("Chess is a sea in which a gnat may drink and an elephant may bathe", "Hindu proverb"),
    Quote("Pawn endings are to Chess what putting is to golf", "Cecil Purdy"),
    Quote("Chess opens and enriches your mind", "Saudin Robovic"),
    Quote("The isolated Pawn casts gloom over the entire chessboard", "Aaron Nimzovich"),
    Quote("For me, Chess is life and every game is like a new life. Every Chess player gets to live many lives in one lifetime", "Eduard Gufeld"),
    Quote("Chess is a terrific way for kids to build self image and self esteem", "Saudin Robovic"),
    Quote("If a ruler does not understand Chess, how can he rule over a kingdom?", "King Khusros II"),
    Quote("Chess is a cold bath for the mind", "Sir John Simon"),
    Quote("Becoming successful at Chess allows you to discover your own personality. That’s what I want for the kids I teach", "Saudin Robovic"),
    Quote("Chess is so inspiring that I do not believe a good player is capable of having an evil thought during the game", "Wilhelm Steinitz"),
    Quote("You are for me the Queen on d8 and I am the Pawn on d7!! ", "GM Eduard Gufeld"),
    Quote("By playing at Chess then, we may learn: First: Foresight...    Second: Circumspection...    Third: Caution...  And lastly, we learn by Chess the habit of not being discouraged by present bad appearances in the state of our affairs, the habit of hoping for a favorable chance, and that of persevering in the secrets of resources", "Benjamin Franklin"),
    Quote("I prefer to lose a really good game than to win a bad one", "David Levy"),
    Quote("Capture of the adverse King is the ultimate but not the first object of the game", "William Steinitz"),
    Quote("When I have White, I win because I am white; When I have Black, I win because I am Bogolyubov", "Bogolyubov"),
    Quote("Every Pawn is a potential Queen", "James Mason"),
    Quote("Chess is in its essence a game, in its form an art, and in its execution a science", "Baron Tassilo"),
    Quote("No price is too great for the scalp of the enemy King", "Koblentz"),
    Quote("In life, as in Chess, ones own Pawns block ones way.  A mans very wealth, ease, leisure, children, books, which should help him to win, more often checkmate him", "Charles Buxton"),
    Quote("Chess is a part of culture and if a culture is declining then Chess too will decline", "Mikhail Botvinnik"),
    Quote("A good sacrifice is one that is not necessarily sound but leaves your opponent dazed and confused", "Rudolph Spielmann"),
    Quote("Chess, like any creative activity, can exist only through the combined efforts of those who have creative talent, and those who have the ability to organize their creative work", "Mikhail Botvinnik"),
    Quote("One bad move nullifies forty good ones", "Horowitz"),
    Quote("Place the contents of the Chess box in a hat, shake them up vigorously, pour them on the board from a height of two feet, and you get the style of Steinitz", "H. E. Bird"),
    Quote("I have never in my life played the French Defence, which is the dullest of all openings", "Wilhelm Steinitz"),
    Quote("Pawns are born free, yet they are everywhere in chains", "Rick Kennedy"),
    Quote("It is not a move, even the best move that you must seek, but a realizable plan", "Eugene Znosko-Borovsky"),
    Quote("Those who say they understand Chess, understand nothing", "Robert Hubner"),
    Quote("Good offense and good defense both begin with good development", "Bruce A. Moon"),
    Quote("Botvinnik tried to take the mystery out of Chess, always relating it to situations in ordinary life. He used to call Chess a typical inexact problem similar to those which people are always having to solve in everyday life", "Garry Kasparov"),
    Quote("A good player is always lucky", "Jose Raul Capablanca"),
    Quote("The sign of a great Master is his ability to win a won game quickly and painlessly", "Irving Chernev"),
    Quote("One of these modest little moves may be more embarrassing to your opponent than the biggest threat", "Siegbert Tarrasch"),
    Quote("Live, lose, and learn, by observing your opponent how to win", "Amber Steenbock"),
    Quote("The older I grow, the more I value Pawns", "Keres"),
    Quote("Everything is in a state of flux, and this includes the world of Chess", "Mikhail Botvinnik"),
    Quote("The beauty of a move lies not in its’ appearance but in the thought behind it", "Aaron Nimzovich"),
    Quote("My God, Bobby Fischer plays so simply", "Alexei Suetin"),
    Quote("You need not play well - just help your opponent to play badly", "Genrikh Chepukaitis"),
    Quote("It is difficult to play against Einstein’s theory --on his first loss to Fischer", "Mikhail Tal"),
    Quote("The only thing Chess players have in common is Chess", "Lodewijk Prins"),
    Quote("Bobby just drops the pieces and they fall on the right squares", "Miguel Najdorf"),
    Quote("We must make sure that Chess will not be like a dead language, very interesting, but for a very small group", "Sytze Faber"),
    Quote("The passion for playing Chess is one of the most unaccountable in the world", "H.G. Wells"),
    Quote("Chess is so interesting in itself, as not to need the view of gain to induce engaging in it; and thence it is never played for money", "Benjamin Franklin"),
    Quote("The enormous mental resilience, without which no Chess player can exist, was so much taken up by Chess that he could never free his mind of this game", "Albert Einstein"),
    Quote("Nowadays, when you’re not a grandmaster at 14, you can forget about it", "Anand Viswanathan"),
    Quote("Do you realize Fischer almost never has any bad pieces? He exchanges them, and the bad pieces remain with his opponents", "Yuri Balashov"),
    Quote("It is always better to sacrifice your opponent’s men", "Savielly Tartakower"),
    Quote("In Chess, as it is played by masters, chance is practically eliminated", "Emanuel Lasker"),
    Quote("You know you’re going to lose. Even when I was ahead I knew I was going to lose  --on playing against Fischer", "Andrew Soltis"),
    Quote("I won’t play with you anymore. You have insulted my friend --when an opponent cursed himself for a blunder", "Miguel Najdorf"),
    Quote("You know, comrade Pachman, I don’t enjoy being a Minister, I would rather play Chess like you", "Che Guevara"),
    Quote("It began to feel as though you were playing against Chess itself --on playing against Robert Fischer", "Walter Shipman"),
    Quote("Checkers is for tramps", "Paul Morphy"),
    Quote("When you play Bobby, it is not a question if you win or lose.  It is a question if you survive", "Boris Spassky"),
    Quote("When you absolutely don’t know what to do anymore, it is time to panic", "John van der Wiel"),
    Quote("We like to think", "Gary Kasparov"),
    Quote("Dazzling combinations are for the many, shifting wood is for the few", "Georg Kieninger"),
    Quote("In complicated positions, Bobby Fischer hardly had to be afraid of anybody", "Paul Keres"),
    Quote("It was clear to me that the vulnerable point of the American Grandmaster (Bobby Fischer) was in double-edged, hanging, irrational positions, where he often failed to find a win even in a won position", "Efim Geller"),
    Quote("I love all positions. Give me a difficult positional game, I will play it.  But totally won positions, I cannot stand them", "Hein Donner"),
    Quote("In Fischer’s hands, a slight theoretical advantage is as good a being a Queen ahead", "Isaac Kashdan"),
    Quote("I still hope to kill Fischer", "Boris Spassky"),
    Quote("Is Bobby Fischer quite sane?", "Salo Flohr"),
    Quote("Robert Fischer is a law unto himself", "Larry Evans"),
    Quote("Fischer is under obligation to nobody", "Joseph Platz"),
    Quote("Bobby Fischer’s current state of mind is indeed a tragedy. One of the worlds greatest Chess players - the pride and sorrow of American Chess", "Frank Brady"),
    Quote("Fischer is an American Chess tragedy on par with Morphy and Pillsbury", "Mig Greengard"),
    Quote("Nonsense was the last thing Fischer was interested in, as far as Chess was concerned", "Elie Agur"),
    Quote("Fischer is the strongest player in the world. In fact, the strongest player who ever lived", "Larry Evans"),
    Quote("If you aren’t afraid of Spassky, then I have removed the element of money", "Jim Slater"),
    Quote("I guess a certain amount of temperament is expected of Chess geniuses", "Ron Gross"),
    Quote("Fischer sacrificed virtually everything most of us weakies (to use his term) value, respect, and cherish, for the sake of an artful, often beautiful board game, for the ambivalent privilege of being its greatest master", "Paul Kollar"),
    Quote("Fischer Chess play was always razor-sharp, rational and brilliant. One of the best ever", "Dave Regis"),
    Quote("Fischer wanted to give the Russians a taste of their own medicine", "Larry Evans"),
    Quote("With or without the title, Bobby Fischer was unquestionably the greatest player of his time", "Burt Hochberg"),
    Quote("Fischer is completely natural. He plays no roles.  He’s like a child. Very, very simple", "Zita Rajcsanyi"),
    Quote("Spassky will not be psyched out by Fischer", "Mike Goodall"),
    Quote("Already at 15 years of age he was a Grandmaster, a record at that time, and his battle to reach the top was the background for all the major Chess events of the 1960", "Tim Harding"),
    Quote("Fischer, who may or may not be mad as a hatter, has every right to be horrified", "Jeremy Silman"),
    Quote("When I asked Fischer why he had not played a certain move in our game, he replied: ‘Well, you laughed when I wrote it down!’", "Mikhail Tal"),
    Quote("I look one move ahead... the best!", "Siegbert Tarrasch"),
    Quote("Fischer prefers to enter Chess history alone", "Miguel Najdorf"),
    Quote("Bobby is the most misunderstood, misquoted celebrity walking the face of this earth", "Yasser Seirawan"),
    Quote("When you don’t know what to play, wait for an idea to come into your opponent’s mind. You may be sure that idea will be wrong", "Siegbert Tarrasch"),
    Quote("There is no remorse like the remorse of Chess", "H. G. Wells"),
    Quote("By this measure (on the gap between Fischer & his contemporaries), I consider him the greatest world champion", "Garry Kasparov"),
    Quote("By the beauty of his games, the clarity of his play, and the brilliance of his ideas, Fischer made himself an artist of the same stature as Brahms, Rembrandt, and Shakespeare", "David Levy"),
    Quote("Chess is a terrible game. If you have no center, your opponent has a freer position. If you do have a center, then you really have something to worry about!", "Siegbert Tarrasch"), Quote("Many Chess players were surprised when after the game, Fischer quietly explained: ’I had already analyzed this possibility’ in a position which I thought was not possible to foresee from the opening", "Mikhail Tal"),
    Quote("Suddenly it was obvious to me in my analysis I had missed what Fischer had found with the greatest of ease at the board", "Mikhail Botvinnik"),
    Quote("The King is a fighting piece. Use it!", "Wilhelm Steinitz"),
    Quote("A thorough understanding of the typical mating continuations makes the most complicated sacrificial combinations leading up to them not only not difficult, but almost a matter of course", "Siegbert Tarrasch"),
    Quote("Bobby Fischer is the greatest Chess genius of all time!", "Alexander Kotov"),
    Quote("The laws of Chess do not permit a free choice: you have to move whether you like it or not", "Emanuel Lasker"),
    Quote("First-class players lose to second-class players because second-class players sometimes play a first-class game", "Siegbert Tarrasch"),
    Quote("Bobby is the finest Chess player this country ever produced. His memory for the moves, his brilliance in dreaming up combinations, and his fierce determination to win are uncanny", "John Collins"),
    Quote("After a bad opening, there is hope for the middle game. After a bad middle game, there is hope for the endgame. But once you are in the endgame, the moment of truth has arrived", "Edmar Mednis"),
    Quote("Weak points or holes in the opponent’s position must be occupied by pieces not Pawns", "Siegbert Tarrasch"),
    Quote("There is only one thing Fischer does in Chess without pleasure: to lose!", "Boris Spassky"),
    Quote("Bobby Fischer is the greatest Chess player who has ever lived", "Ken Smith"),
    Quote("Up to this point White has been following well-known analysis. But now he makes a fatal error: he begins to use his own head", "Siegbert Tarrasch"),
    Quote("Fischer was a master of clarity and a king of artful positioning. His opponents would see where he was going but were powerless to stop him", "Bruce Pandolfini"),
    Quote("No other master has such a terrific will to win. At the board he radiates danger, and even the strongest opponents tend to freeze, like rabbits when they smell a panther. Even his weaknesses are dangerous. As white, his opening game is predictable - you can make plans against it - but so strong that your plans almost never work. In the middle game his precision and invention are fabulous, and in the end game you simply cannot beat him", "Anonymous German Expert"),
    Quote("White lost because he failed to remember the right continuation and had to think up the moves himself", "Siegbert Tarrasch"),
    Quote("Not only will I predict his triumph over Botvinnik, but I’ll go further and say that he’ll probably be the greatest Chess player that ever lived", "John Collins"),
    Quote("I consider Fischer to be one of the greatest opening experts ever", "Keith Hayward"),
    Quote("I like to say that Bobby Fischer was the greatest player ever. But what made Fischer a genius was his ability to blend an American freshness and pragmatism with Russian ideas about strategy", "Bruce Pandolfini"),
    Quote("At this time Fischer is simply a level above all the best Chessplayers in the world", "John Jacobs"),
    Quote("I have always a slight feeling of pity for the man who has no knowledge of Chess", "Siegbert Tarrasch"),
    Quote("There’s never before been a Chess player with such a thorough knowledge of the intricacies of the game and such an absolutely indomitable will to win. I think Bobby is the greatest player that ever lived", "Lisa Lane"),
    Quote("He who takes the Queen’s Knight’s Pawn will sleep in the streets", "Anonymous"),
    Quote("I had a toothache during the first game. In the second game I had a headache. In the third game it was an attack of rheumatism. In the fourth game, I wasn’t feeling well. And in the fifth game? Well, must one have to win every game?", "Siegbert Tarrasch"),
    Quote("The stomach is an essential part of the Chess master", "Bent Larsen"),
    Quote("We must make sure that Chess will not be like a dead language, very interesting, but for a very small group", "Sytze Faber"),
    Quote("I’m not a materialistic person, in that, I don’t suffer the lack or loss of money.  The absence of worldly goods I don’t look back on. For Chess is a way I can be as materialistic as I want without having to sell my soul ", "Jamie Walter Adams"),
    Quote("These are not pieces, they are men! For any man to walk into the line of fire will be one less man in your army to fight for you. Value every troop and use him wisely, throw him not to the dogs as he is there to serve his King", "Jamie Walter Adams"),
    Quote("Chess isn’t a game of speed, it is a game of speech through actions", "Matthew Selman"),
    Quote("Life like Chess is about knowing to do the right move at the right time", "Kaleb Rivera"))
}
