import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const srcDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '../src');
const prelude =
  '// Generated by .build/index.mjs to export the bots directory from src/index.ts\n//\n' +
  '// Relaunch ui/build to regenerate (the bots directory is not watched).\n\n';
const barrel = fs
  .readdirSync(path.join(srcDir, 'bots'))
  .filter(file => file.endsWith('.ts'))
  .map(file => `export * from './bots/${path.basename(file, '.ts')}';`)
  .join('\n');

fs.writeFileSync(path.join(srcDir, 'index.gen.ts'), prelude + barrel);
