// This file is generated by bin/gen/icons.py from public/images/svg-icons. Do not edit it

package lila.ui

enum Icon:
  case accountCircle
  case addPhotoOutline
  case agent
  case analogTv
  case antichess
  case archeryTarget
  case arrowDownRight
  case arrowThruApple
  case arrowUpRight
  case atom
  case back
  case barChart
  case barGraph
  case bellOutline
  case berserk
  case book
  case bubbleConvo
  case bubbleSpeech
  case bullet
  case bullseye
  case cancel
  case cautionCircle
  case cautionTriangle
  case chasingArrows
  case checkmark
  case clipboard
  case clock
  case cogs
  case cpu
  case crazyhouse
  case crown
  case crownElite
  case dieSix
  case disc
  case discBig
  case discBigOutline
  case discOutline
  case downTriangle
  case download
  case envelope
  case expand
  case externalArrow
  case eye
  case feather
  case fire
  case flagChessboard
  case flagKingHill
  case flagOutline
  case flagRacingKings
  case flameBlitz
  case forward
  case funnel
  case gear
  case globe
  case graduateCap
  case greaterThan
  case group
  case hamburger
  case heart
  case heartOutline
  case ibeam
  case infoCircle
  case inkQuill
  case internalArrow
  case jumpFirst
  case jumpLast
  case jumpNext
  case jumpPrev
  case keypad
  case language
  case lessThan
  case lineGraph
  case link
  case list
  case logo
  case mic
  case microscope
  case minusButton
  case moreTriangle
  case move
  case multiboard
  case mute
  case notAllowed
  case oneHalf
  case padlock
  case paperAirplane
  case pause
  case pencil
  case phoneMobile
  case playTriangle
  case plusButton
  case power
  case prune
  case rabbit
  case radioTower
  case randomColor
  case reload
  case rssFeed
  case screenDesktop
  case search
  case shareAndroid
  case shareIos
  case shield
  case star
  case starOutline
  case storm
  case studyBoard
  case switch
  case swords
  case tag
  case target
  case threeCheckStack
  case thumbsUp
  case tools
  case trash
  case trophy
  case tshirt
  case turtle
  case ultraBullet
  case upTriangle
  case uploadCloud
  case user
  case voice
  case wings
  case x
  case zoomIn
  def name: String = productPrefix

object Icon:
  import play.api.libs.json.*
  given Writes[Icon] = Writes(icon => JsString(icon.name))

  val byName = values.mapBy(_.name)

  val rtlMirrored: Set[Icon] = Set(
    greaterThan,
    jumpFirst,
    jumpLast,
    jumpNext,
    jumpPrev,
    lessThan,
    playTriangle,
    wings
  )
