/*
 * This source is generated by bin/gen/licon.py. Run licon.py after changing public/font/lichess.sfd
 *
 * Constant names and values are pulled from private use characters defined in the sfd file.
 *
 * Character names can be edited in fontforge's "glyph info" dialog, or by editing the StartChar: line that
 * begins each character chunk in lichess.sfd
 *
 * To make these characters visible in your editor, install the lichess.ttf font (which is also generated by
 * licon.py) and then add it to your editor's font list.
 */

package lila.ui

opaque type Icon = String
object Icon:
  def apply(char: String): Icon            = char
  extension (icon: Icon) def value: String = icon
  given scalalib.Iso.StringIso[Icon]       = scalalib.Iso.string(apply, value)
  import play.api.libs.json.{ Writes, JsString }
  given iconWrites: Writes[Icon] = icon => JsString(Icon.value(icon))
  val Tools: Icon                = "" // e000
  val Bullseye: Icon             = "" // e001
  val Agent: Icon                = "" // e002
  val Mic: Icon                  = "" // e003
  val BarChart: Icon             = "" // e004
  val InfoCircle: Icon           = "" // e005
  val ScreenDesktop: Icon        = "" // e006
  val PhoneMobile: Icon          = "" // e007
  val Multiboard: Icon           = "" // e008
  val HeartOutline: Icon         = "" // e009
  val FlagRacingKings: Icon      = "" // e00a
  val Crazyhouse: Icon           = "" // e00b
  val Tshirt: Icon               = "" // e00c
  val Heart: Icon                = "" // e00d
  val RadioTower: Icon           = "" // e00e
  val BellOutline: Icon          = "" // e00f
  val Disc: Icon                 = "" // e010
  val Wings: Icon                = "" // e011
  val DiscOutline: Icon          = "" // e012
  val Handset: Icon              = "" // e013
  val ArrowThruApple: Icon       = "" // e014
  val CautionTriangle: Icon      = "" // e015
  val Link: Icon                 = "" // e016
  val Rabbit: Icon               = "" // e017
  val NodeBranching: Icon        = "" // e018
  val Gear: Icon                 = "" // e019
  val Reload: Icon               = "" // e01a
  val DieSix: Icon               = "" // e01b
  val FlagKingHill: Icon         = "" // e01c
  val FlameBlitz: Icon           = "" // e01d
  val Feather: Icon              = "" // e01e
  val Turtle: Icon               = "" // e01f
  val FlagChessboard: Icon       = "" // e020
  val ArcheryTarget: Icon        = "" // e021
  val ThreeCheckStack: Icon      = "" // e022
  val UploadCloud: Icon          = "" // e023
  val ExternalArrow: Icon        = "" // e024
  val AnalogTv: Icon             = "" // e025
  val RssFeed: Icon              = "" // e026
  val StudyBoard: Icon           = "" // e027
  val Shield: Icon               = "" // e028
  val InkQuill: Icon             = "" // e029
  val Target: Icon               = "" // e02a
  val Crown: Icon                = "" // e02b
  val LineGraph: Icon            = "" // e02c
  val GraduateCap: Icon          = "" // e02d
  val PaperAirplane: Icon        = "" // e02e
  val ZoomIn: Icon               = "" // e02f
  val Expand: Icon               = "" // e030
  val Atom: Icon                 = "" // e031
  val List: Icon                 = "" // e032
  val Antichess: Icon            = "" // e033
  val Microscope: Icon           = "" // e034
  val ChasingArrows: Icon        = "" // e035
  val CrownElite: Icon           = "" // e036
  val Funnel: Icon               = "" // e037
  val Checkmark: Icon            = "" // e038
  val InternalArrow: Icon        = "" // e039
  val PlayTriangle: Icon         = "" // e03a
  val GreaterThan: Icon          = "" // e03b
  val LessThan: Icon             = "" // e03c
  val DiscBig: Icon              = "" // e03d
  val DiscBigOutline: Icon       = "" // e03e
  val X: Icon                    = "" // e03f
  val ArrowDownRight: Icon       = "" // e040
  val ArrowUpRight: Icon         = "" // e041
  val PlusButton: Icon           = "" // e042
  val MinusButton: Icon          = "" // e043
  val Fire: Icon                 = "" // e044
  val DownTriangle: Icon         = "" // e045
  val UpTriangle: Icon           = "" // e046
  val Bullet: Icon               = "" // e047
  val Swords: Icon               = "" // e048
  val JumpLast: Icon             = "" // e049
  val JumpFirst: Icon            = "" // e04a
  val JumpNext: Icon             = "" // e04b
  val JumpPrev: Icon             = "" // e04c
  val Pause: Icon                = "" // e04d
  val Hamburger: Icon            = "" // e04e
  val Globe: Icon                = "" // e04f
  val Book: Icon                 = "" // e050
  val BarGraph: Icon             = "" // e051
  val Keypad: Icon               = "" // e052
  val Berserk: Icon              = "" // e053
  val Padlock: Icon              = "" // e054
  val FlagOutline: Icon          = "" // e055
  val BubbleSpeech: Icon         = "" // e056
  val BubbleConvo: Icon          = "" // e057
  val Envelope: Icon             = "" // e058
  val Group: Icon                = "" // e059
  val Trophy: Icon               = "" // e05a
  val ThumbsUp: Icon             = "" // e05b
  val Back: Icon                 = "" // e05c
  val CautionCircle: Icon        = "" // e05d
  val NotAllowed: Icon           = "" // e05e
  val RandomColor: Icon          = "" // e05f
  val Pencil: Icon               = "" // e060
  val Cogs: Icon                 = "" // e061
  val Tag: Icon                  = "" // e062
  val Clock: Icon                = "" // e063
  val Trash: Icon                = "" // e064
  val User: Icon                 = "" // e065
  val StarOutline: Icon          = "" // e066
  val Star: Icon                 = "" // e067
  val MoreTriangle: Icon         = "" // e068
  val Eye: Icon                  = "" // e069
  val Power: Icon                = "" // e06a
  val Download: Icon             = "" // e06b
  val Search: Icon               = "" // e06c
  val Forward: Icon              = "" // e06d
  val UltraBullet: Icon          = "" // e06e
  val Storm: Icon                = "" // e06f
  val Clipboard: Icon            = "" // e070
  val Cancel: Icon               = "" // e071
  val Ibeam: Icon                = "" // e072
  val Voice: Icon                = "" // e073
  val Mask: Icon                 = "" // e074
  val Move: Icon                 = "" // e075
  val OneHalf: Icon              = "" // e076
  val Mute: Icon                 = "" // e077
  val AccountCircle: Icon        = "" // e078
  val Logo: Icon                 = "" // e079
