#!/bin/bash
# from https://github.com/gre/play-packages/blob/master/ArchLinux_AUR/playframework/skeleton_playapp

NAME=`basename $0`
. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/$NAME
. /etc/profile.d/jre.sh

USER=${USER-"root"}
pidfile=$PLAY_APP/RUNNING_PID
PID=`cat $pidfile 2> /dev/null`
[[ -e $pidfile ]] && ( [ -n "`ps -p $PID | grep $PID`" ] || rm -f $pidfile) # rm pidfile if not process is running
PID=`cat $pidfile 2> /dev/null`

case $1 in
  start)
    stat_busy "Starting Play framework $PLAY_APP app"
    if [[ -z $PID ]] && su - $PLAY_USER -c "cd $PLAY_APP; bin/prod/start_wait"; then
      add_daemon $NAME
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping Play framework $PLAY_APP app - PID: $PID"
    if [[ ! -z $PID ]] && su - $PLAY_USER -c "cd $PLAY_APP && bin/prod/stop"; then
      rm_daemon $NAME
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1

esac
