#!/usr/bin/env bash

UI_DIR=$(dirname $(readlink -f  "${BASH_SOURCE:-$0}"))

if [ ! -f "$UI_DIR/../node_modules/@build/bleep/dist/main.js" ]; then
  cd "$UI_DIR"
  yarn install
  cd "$UI_DIR/@build/bleep"
  yarn tsc
fi

cd "$UI_DIR/@build/bleep"
yarn --silent run go "$@"
