#!/usr/bin/env bash

UI_DIR=$(dirname $(readlink -f  "${BASH_SOURCE:-$0}"))
cd "$UI_DIR"

if [ ! -f "$UI_DIR/../node_modules/@build/bleep/dist/main.js" ]; then
  yarn install
fi

cd "$UI_DIR/@build/bleep"

yarn --silent run go "$@"
