#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE:-$0}")/.build"

update=false
if expr "$*" : '.*--update' >/dev/null; then
  update=true
fi
if $update || [ ! -d "node_modules" ]; then
  npm install --silent --no-progress --no-package-lock
fi
if $update || [ ! -d "dist" ]; then
  ./node_modules/.bin/tsc
fi
node --input-type=module dist/main.js "$@"
