#!/usr/bin/env bash

set -e

MIN_NODE="v22.6.0"

CUR_NODE=$(node -v 2>/dev/null || echo "v0.0.0")
LOWEST="$(printf "%s\n%s" "$MIN_NODE" "$CUR_NODE" | sort -V | head -n 1)"
if [ "$LOWEST" != "$MIN_NODE" ]; then
  echo "Nodejs $MIN_NODE or later is required."
  exit 1
fi

cd "$(dirname "${BASH_SOURCE:-$0}")/.build"

if [[ " $* " != *" --no-corepack "* ]]; then
  if ! corepack enable >/dev/null 2>&1; then
    echo "Corepack not available. Try a userland node such as nvm."
  fi
fi

pnpm install --silent --ignore-workspace

node --experimental-strip-types --no-warnings src/main.ts "$@"
