#!/bin/sh -e
. bin/lilarc

target=${1-dev}

mkdir -p public/compiled

ts_apps="common chess ceval game tree"
apps="site chat2 challenge2 notify2 learn insight editor puzzle round2 analyse lobby tournament tournamentSchedule simul perfStat dasher"

prll_sh=${PRLLSH-/etc/profile.d/prll.sh}

build_ts() {
  cd ui/$1
  rm -rf node_modules/types
  rm -rf node_modules/common
  rm -rf node_modules/chess
  npm install --no-optional
  npm run compile
  cd -
}

build() {
  app=$1
  echo "Building $app"
  cd ui/$app
  rm -rf node_modules/types
  rm -rf node_modules/common
  rm -rf node_modules/chess
  rm -rf node_modules/game
  rm -rf node_modules/tree
  rm -rf node_modules/ceval
  npm install --no-optional && gulp $target
  cd -
}

if [ -f $prll_sh ]; then # parallel execution!
  export PRLL_NRJOBS="${PRLL_NRJOBS-10}"
  echo "Building up to $PRLL_NRJOBS in parallel!"
  . $prll_sh
  prll build_ts $ts_apps
  prll build $apps
else # sequential execution
  for app in $ts_apps; do build_ts $app; done
  for app in $apps; do build $app; done
fi
