package lila.fishnet

import org.joda.time.DateTime

case class Instance(
    _id: Instance.Id, // generated by the client, changes on restart
    clientKey: Client.Key, // API key used to authenticate and assign move or analysis
    version: Instance.Version,
    stats: Stats,
    createdAt: DateTime,
    lastSeenAt: DateTime) {

  def id = _id
}

object Instance {
  case class Id(value: String) extends AnyVal
  case class Version(value: String) extends AnyVal
}
