package lila.fishnet

import org.joda.time.DateTime

case class Instance(
    _id: String, // generated by the client, changes on restart
    clientKey: String, // API key used to authenticate and assign move or analysis
    version: String,
    stats: Stats,
    createdAt: DateTime,
    lastSeenAt: DateTime) {

  def id = _id
}
