name: Validate devenv

on:
  push:
    paths: &devenv_paths
      - '.github/workflows/devenv.yml'
      - '.node_version'
      - 'devenv.*'
      - 'flake.*'
      - '**/package.json'
      - '**/pnpm-lock.yaml'
      - '**/pnpm-workspace.yaml'

  pull_request:
    paths: *devenv_paths

jobs:
  validate-devenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: Make sure `./ui/build` requirements are satisfied
        shell: devenv shell -- bash -e {0}
        run: |
          ./ui/build --help
