name: Validate Piece CSS

on:
  push:
    paths:
      - '.github/workflows/piece-sets.yml'
      - 'bin/gen/piece-css.ts'
      - 'public/piece/**'
      - 'public/piece-css/**'
  pull_request:
    paths:
      - '.github/workflows/piece-sets.yml'
      - 'bin/gen/piece-css.ts'
      - 'public/piece/**'
      - 'public/piece-css/**'

jobs:
  validate-piece-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
      - run: pnpm run piece-css
      - name: Verify generated piece CSS matches SVG files
        run: git diff --exit-code
