name: Translations

on:
  push:
    paths:
      - '.github/workflows/translations.yml'
      - 'translation/**'
      - 'bin/trans-lint'
      - 'ui/.build/src/i18n.ts'
      - 'modules/coreI18n/src/main/key.scala'
  pull_request:
    paths:
      - '.github/workflows/translations.yml'
      - 'translation/**'
      - 'bin/trans-lint'
      - 'ui/.build/src/i18n.ts'
      - 'modules/coreI18n/src/main/key.scala'

jobs:
  xmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9 # 1.6.3
        with:
          packages: libxml2-utils
          version: 1.0
      - name: Validate translation files
        run: xmllint --noout --dtdvalid translation/resources.dtd translation/**/*.xml

  trans-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Lint translation files
        run: ./bin/trans-lint translation/dest/*/*.xml

  i18n-key-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install
      - run: pnpm i18n-file-gen
      - run: ./ui/build --i18n
      - name: i18n files up-to-date check
        run: |
          git status --porcelain
          git diff
          if [[ -n $(git status --porcelain) ]]; then
              echo "i18n files are out of date. Please run `pnpm i18n-file-gen` and `./ui/build --i18n` and commit the changes.";
              exit 1;
          fi
